app/static/js/app.js
=> Assume shutdown when server fails to respond

app/static/css/style.css, app/static/js/app.js, app/templates/index.html
=> Adding shutdown confirmation

README.md, quick-install
=> Adding installation instructions to README

README.md
Clarify security considerations and install options
=> Further tweaks to README

app/static/css/style.css, app/templates/index.html
=> Rearranging modifier keys

README.md
=> Adding hardware requirements

app/local_system.py, app/main.py, app/static/js/app.js, app/templates/index.html
=> Adding support for reboot

README.md
=> Document supported VGA to HDMI adapter

app/local_system.py
=> Fix restart parameter on shutdown command

quick-install
=> Adding libffi-dev to list of ansible requirements

scripts/usb-gadget/init-usb-gadget
Reformats the keyboard HID descriptor generation so that it's more self-documenting.
=> Refactor keyboard HID descriptor

app/static/js/app.js
Refactoring the keystroke processing for better code sharing with the incoming paste functionality (#113).
=> Refactor JS keystroke processing

app/hid/mouse.py, app/js_to_hid.py, app/main.py, app/static/js/app.js
Add mouse button support to events & allow for dragging (didn't get a chance to test yet, implemented according to https://wiki.osdev.org/USB_Human_Interface_Devices).
=> Mouse tweaks

app/js_to_hid.py, app/main.py, app/request_parsers/keystroke.py, app/static/js/app.js, app/tests/request_parsers/test_keystroke.py
Moves the keystroke message parsing to a new module, adds unit tests, changes some property names. This ensures that incoming data is validated before further processing.
=> Make keystroke processing more robust

app/templates/index.html
This is basically just to make the merge of #113 a little easier
=> Add a div to contain the entire app

app/static/css/style.css
Lora should be the default non-header font.
=> Change Lora to the default font everywhere

app/main.py
Ensure that the web server reloads when any of the frontend HTML/JS/CSS files change.
=> Find all frontend files by glob pattern

app/templates/custom-elements/content-tooltip.html, app/templates/index.html
=> Fix Modifier keys tooltip / add tooltip-top-left

app/static/css/style.css, app/static/js/app.js, app/templates/index.html
Lets try this again. 
Shutdown Dialog to Modal.
=> Shutdown modal

app/static/css/navbar.css, app/static/css/style.css, app/static/js/app.js, app/templates/components/navbar.html, app/templates/custom-elements/paste-overlay.html, app/templates/index.html
Currently the only option that maintains aspect ratio is default.
=> Add support for fullscreen mode

app/static/js/app.js
Refactoring the paste logic so that we can send text values without assuming it's from a paste. Makes way for #223.
=> Refactor paste functionality

app/request_parsers/keystroke.py, app/tests/request_parsers/test_keystroke.py
Fixes #171
I hope this is what you were looking for, not much info on this one. Also isort fails for me so I might need some guidance on that.
=> Gracefully handle keystroke requests with missing fields

app/request_parsers/mouse_event.py, app/tests/request_parsers/test_mouse_event.py
Fixes #168 
~This will probably call CI? What are you using for python code to make it "Prettier"?~
=> Gracefully handle mouse_event requests with missing fields

app/request_parsers/keystroke.py, app/request_parsers/mouse_event.py, app/tests/request_parsers/test_mouse_event.py
Add a specific exception class for missing fields.
=> Refactor mouse event message parsing

app/hid/write.py
Users were reporting TinyPilot locking up when there were too many writes to the HID interface, likely because there were lots of zombie threads that were waiting on blocked IO. Looking more closely at the IO APIs, we can just skip the threads entirely and use non-blocking IO primitives.
Related: https://github.com/mtlynch/tinypilot/issues/246
=> Use non-blocking writes to write to HID interface

app/hid/keyboard.py
Reverts mtlynch/tinypilot#252
This caused keypresses to repeat forever.
=> Revert "Consolidate key press and release writes to HID interface"

app/static/css/style.css, app/static/js/app.js, app/templates/custom-elements/remote-screen.html, app/templates/index.html
Here is a start for the mobile input portion, we need to work on key mapping though. Probably related but text is actually being typed into the input on mobile, that would need to be prevented.
Keyboard opens on default and full screen views. On android you can hide the keyboard with the back arrow, I have not tested on iOS.
I Dynamically created the input, but it can easily be included in the html.
---
**Edit by mtlynch@**
Fixes #46
^^^ Putting that line in the PR description auto-closes the linked issue when we merge it.
=> Mobile Keyboard Input

app/static/js/app.js, app/templates/custom-elements/remote-screen.html, app/templates/index.html
Reverts mtlynch/tinypilot#223
It turns out that this broke fullscreen mode on desktop.
=> Revert "Mobile Keyboard Input"

app/main.py, app/static/js/app.js, app/templates/custom-elements/remote-screen.html, app/templates/index.html
=> Implement adaptive throttling for mouse events

app/static/js/app.js
Uncaught TypeError: Cannot read property 'classList' of null
=> Fix Uncaught TypeError

app/js_to_hid.py
=> Add key mapping for OS X meta key

app/static/js/app.js, app/templates/components/navbar.html
Add screenshot option
Fixes #313
=> Add screenshot option

app/templates/custom-elements/key-history-card.html
This fixes a regression caused in 0386046cce0c3ea4e4a29d6e2cdb54dd5ef8d1b1
=> Make key card heights uniform

app/static/js/shutdown.js, app/templates/custom-elements/shutdown-dialog.html
This achieves a better separationg between HTTP logic and UI logic between the shutdown dialog and the REST call.
=> Add a controller for calling /api/shutdown endpoint

app/static/js/controllers.js
The original implementation was pretty hacked together, so this refactors the code to be more reusable from other API controllers and makes abstraction boundaries more clear.
=> Refactor the logic in controllers.js

app/static/css/navbar.css
Fixes https://github.com/mtlynch/tinypilot/issues/432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/444)
=> Fix Safari menu bug

app/api.py, app/update.py
Closes https://github.com/mtlynch/tinypilot/issues/430.
Implements `GET /api/update` and `PUT /api/update` as described, and adds a `UpdateJob` in `update.py` to handle the involved operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/441)
=> Make /api/update asynchronous

.pylintrc, app/api.py, app/git.py, app/hid/mouse.py, app/hid/write.py, app/js_to_hid.py, app/local_system.py, app/main.py, app/request_parsers/keystroke.py, app/request_parsers/mouse_event.py, app/tests/hid/test_mouse.py, app/tests/request_parsers/test_keystroke.py, app/update.py, dev-scripts/build-python, dev_requirements.txt
=> Integrate pylint into the Python build

app/update.py
Make public functions appear before private functions.
=> Reorder functions in update.py

app/update.py
=> Redirect the output of the background update process to log files

ARCHITECTURE.md, CONTRIBUTING.md, README.md
Add CONTRIBUTING.md and ARCHITECTURE.md docs to the repo.
Credit to this blog post for inspiration: https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html
Fixes #440
=> Add more developer documentation

dev-scripts/build-python, dev_requirements.txt
It was incorrectly picking up code coverage on test_ files.
=> Fix code coverage

dev-scripts/check-trailing-newline
https://google.github.io/styleguide/shellguide.html
=> Adjust check-trailing-newline to fit style conventions

dev-scripts/check-trailing-newline, dev-scripts/check-trailing-whitespace
=> Exclude files outside source control from whitespace checks

CONTRIBUTING.md
=> Clarify CONTRIBUTING.md to say we no longer obey Google JS style

app/templates/custom-elements/debug-dialog.html
Make it a little bigger
Adjust heading text on the shareable URL view
Add border around log div
Add more style to the shareable URL
=> Tweak UI of debug dialog

app/main.py
=> Disable flask's caching when we're running in debug mode

app/templates/custom-elements/connection-indicator.html
Fixes https://github.com/mtlynch/tinypilot/issues/488
=> Make connection label more expressive

app/socket_api.py
Reverts mtlynch/tinypilot#559
This is still causing issues for some users. Need more investigating.
=> Revert "Remove CORS workaround for Flask-SocketIO"

app/static/js/app.js, app/templates/custom-elements/update-dialog.html, app/templates/index.html
Basically the same as https://github.com/mtlynch/tinypilot/pull/590
=> Migrate update overlay to use new overlay component

app/static/js/app.js, app/templates/custom-elements/debug-dialog.html, app/templates/index.html
Hooray, this is the last one 🎉 
In addition to [the usual](https://github.com/mtlynch/tinypilot/pull/590) the custom keystroke disabling was removed.
Also eventually fixes https://github.com/mtlynch/tinypilot/issues/583
=> Migrate debug overlay

README.md
=> Clarify TinyPilot's install location in README

app/static/js/app.js
This was an old element that was deleted long ago. Neither the class nor the handler exist any longer.
=> Delete manual-modifier-btn handler

app/update_settings.py, app/update_settings_test.py, requirements.txt
Copied the [`update_settings` module](https://github.com/tiny-pilot/tinypilot-pro/blob/master/app/update_settings.py) (+ [`update_settings_tests`](https://github.com/tiny-pilot/tinypilot-pro/blob/master/app/update_settings_test.py)) from tinypilot-pro.
This PR doesn't bring in any [code that actually uses this module](https://github.com/tiny-pilot/tinypilot-pro/blob/master/app/update.py#L102-L118). 
Related to #629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/635)
=> Backport update_settings module.

app/update/status_test.py
This also fixes some bugs in tests due to incorrect module traversal.
=> Add missing __init__.py files to directories where they're absent

dev-scripts/build-python, scripts/update-service
It previously wasn't linting it because it wasn't traversing the scripts/ directory.
=> Fix pylint command for update script

app/templates/custom-elements/change-hostname-dialog.html, app/templates/custom-elements/debug-dialog.html, app/templates/custom-elements/shutdown-dialog.html, app/templates/custom-elements/update-dialog.html
Adjusting h3 elements in overlay dialogs so that they all have consistent title casing.
=> Give dialog headings consistent capitalization

app/hid/keyboard.py
This comment was from when send_keystroke both sent and released keys, but those functions are now separate.
=> Remove outdated comment

app/json_response.py
Fixes https://github.com/mtlynch/tinypilot/issues/506.
~Waiting for https://github.com/tiny-pilot/tinypilot-pro/pull/139 to be merged, to not break Pro when merging community into it.~ Done
=> Remove obsolete methods

app/js_to_hid_test.py
We should be importing at the module level, not the function level, so fixing js_to_hid_test.
=> Fix style violation in import

app/api.py, app/static/js/controllers.js, app/templates/custom-elements/video-settings-dialog.html
[Video demo](https://www.loom.com/share/5d79b2e867ba41c7a99e039b2a4d4d89).
Fixes #677
=> Add "Reset Defaults" button in Video Settings dialog

app/static/js/app.js
Waiting for https://github.com/tiny-pilot/tinypilot-pro/pull/152 to be merged.
=> Remove obsolete code from event refactoring

app/templates/custom-elements/change-hostname-dialog.html, app/templates/custom-elements/connection-indicator.html, app/templates/custom-elements/content-tooltip.html, app/templates/custom-elements/countdown-timer.html, app/templates/custom-elements/error-dialog.html, app/templates/custom-elements/key.html, app/templates/custom-elements/keystroke-history-event.html, app/templates/custom-elements/keystroke-history.html, app/templates/custom-elements/menu-bar.html, app/templates/custom-elements/on-screen-keyboard.html, app/templates/custom-elements/overlay-panel.html, app/templates/custom-elements/progress-spinner.html, app/templates/custom-elements/remote-screen.html, app/templates/custom-elements/shutdown-dialog.html, app/templates/custom-elements/status-bar.html, app/templates/custom-elements/update-dialog.html
Fixes #718
Hi @mtlynch, how does this look?
Let me know if this needs any changes.
Thanks
=> Refactor attachShadow calls

CONTRIBUTING.md, dev-scripts/remote-scripts/README.md, dev-scripts/remote-scripts/pull
This is a demonstration of my idea that I outlined in https://github.com/tiny-pilot/tinypilot-pro/issues/120.
The remote scripts are executed via SSH in the way described in the README. This is only for the backend repo so far, not for ansible repo. In the first step this PR is more to showcase the general approach.
The `pull` script allows to update the device’s backend with the latest changes of some branch. For me personally that would be enough, because I mostly use the device for testing out my branches and verifying that they also work in a production environment. I rarely iterate code directly on the Pi, so going the roundtrip via Git would be viable for me. In order to avoid excessive commits should you have to iterate, you could either amend and force-push, or interactively …
=> Proposal: reduce build/test feedback loop through remote procedures

app/request_parsers/keystroke_test.py
As discussed in https://github.com/tiny-pilot/tinypilot/pull/733.
The diff came out quite interesting, it’s actually easier to review the whole file in this case.
=> Group related keystroke tests

app/templates/custom-elements/overlay-panel.html
Resolves #715.
From initial PR #701 with UI update from Michael's review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/782)
=>  Introduce general x button for closing overlays

app/templates/custom-elements/update-dialog.html
I just tried an update that took slightly under 6m so we need a little bit more buffer in case of a slow network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/788)
=> Increase update timeout to 8m

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/791)
=> Document TinyPilot's conventions for web components

dev_requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/840)
=> Upgrade to YAPF 0.31.0

app/templates/custom-elements/remote-screen.html
Resolves #851
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/874)
=> Fix full screen to support more browsers

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/869)
=> Add more detail about TinyPilot's dependencies

app/static/js/janus.js, app/templates/custom-elements/remote-screen.html, app/templates/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/883)
=> Webrtc integration

app/static/js/janus.js, app/templates/custom-elements/remote-screen.html, app/templates/index.html
This PR is meant to integrate tinypilot with Janus and uStreamer for receiving video over WebRTC.
Notes:
The content of `janus.js` was copied from: https://github.com/meetecho/janus-gateway/blob/master/html/janus.js
However, since you'll be running an instance of Janus on the tinypilot machine this code can probably be downloaded directly from there. But I'm not too sure about the nginx configs to point it to the right location.
The other dependency is the webrtc-adapter. Apparently this is needed by `janus.js`. It is mentioned here: https://janus.conf.meetecho.com/docs/JS.html
The code added to `remote-screen.html` doesn't do much other than confirming the connection to Janus and uStreamer is working.
See #877
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Proof of concept: Add WebRTC H264 to frontend

CONTRIBUTING.md
Resolves https://github.com/tiny-pilot/tinypilot/issues/884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/895)
=> Add element naming conventions to CONTRIBUTING.md.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/896)
=> enhancing README with information about the relevant changes and how this information was obtained

app/static/css/style.css, app/static/js/app.js, app/templates/custom-elements/menu-bar.html
Part of https://github.com/tiny-pilot/tinypilot/issues/785#issuecomment-1025139976; based on https://github.com/tiny-pilot/tinypilot/pull/899.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/900)
=> Add “Wake on LAN” menu item

app/static/css/style.css, app/static/js/app.js, app/templates/custom-elements/menu-bar.html
Part of https://github.com/tiny-pilot/tinypilot/issues/785#issuecomment-1025139976; based on https://github.com/tiny-pilot/tinypilot/pull/900.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/901)
=> Remove “Upgrade to Pro” menu item

app/static/css/style.css, app/static/js/app.js, app/templates/custom-elements/feature-pro-dialog.html, app/templates/custom-elements/menu-bar.html
Part of https://github.com/tiny-pilot/tinypilot/issues/785#issuecomment-1025139976; based on https://github.com/tiny-pilot/tinypilot/pull/901.
Also a small fix: we don’t use periods in titles anywhere else, so I’ve removed that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/902)
=> Change wording in button label (pro dialog)

README.md, WEBRTC.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/907)
=> adds WEBRTC.md for documentation on webrtc specific topics

app/hid/keycodes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/910)
=> Document the source of the USB HID keycodes

quick-install
#929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/930)
=> add 64bit warning

quick-install
Add {...} this ensures the entire script is downloaded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/966)
=> ensure the entire script is downloaded

quick-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/968)
=> Rephrase comment in quick-install script

app/static/js/webrtc-video.js
Resolves https://github.com/tiny-pilot/tinypilot/issues/956.
- No functional changes.
- Add a reference to [our general H.264 guide](https://github.com/tiny-pilot/ustreamer/blob/master/docs/h264.md)
- Document all learnings that came up when writing the guide. These comments are partially overlapping with the guide, but I still think it’s good to have them all here as well, so that we have the complete picture. There is also some background info, which we deliberately left out in the guide, to keep it focussed.
- Regarding the MJPEG failover, I realized that the `Janus.error` callback is probably supposed to be the main one to handle this case. It’s also called first, and it’s called always. The `Plugin.onremotetrack` (with `added=false`) is invoked afterwards, if at all. I think it’s …
=> WebRTC: Extend and refine internal documentation

app/templates/custom-elements/about-dialog.html, app/templates/custom-elements/credit-box.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/977)
=> About page hacky suggestions

.circleci/config.yml
Related discussion: https://github.com/tiny-pilot/gatekeeper/issues/31#issuecomment-1164896821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1030)
=> Move LATEST bundle index file to version-index folder

get-tinypilot.sh
Reimplementation of https://github.com/tiny-pilot/tinypilot/pull/966
This PR adds a code block (i.e. `{...}`) around the majority of the code to ensure that the entire file is evaluated before it is executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1052)
=> Ensure that `get-tinypilot.sh` is fully downloaded before execution.

Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1061)
=> Fix hash bang comments in Dockerfile.

get-tinypilot.sh
Resolves https://github.com/tiny-pilot/tinypilot/issues/1069.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1074)
=> Set `/opt/tinypilot-updater` directory ownership to `root`

app/hid/keyboard.py
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1094"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Explain keyboard release behavior in more detail

README.md
This appears to be the current location of the log file collection command
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1135"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Update log file collection command

.circleci/config.yml, .lintianignore, COPYRIGHT, debian-pkg/Dockerfile, debian-pkg/debian/rules, debian-pkg/debian/tinypilot.install
⚠️  This PR is not meant to be merged.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1203"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> POC build Debian package using debhelper without fileroot hack.

ansible-role/defaults/main.yml
Thie updates to the latest and greatest version of uStreamer on Bullseye to pull in some bugfixes that could benefit TinyPilot.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1345"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Update uStreamer version to v5.38

.eslintrc.cjs
We don't currently violate any of these, but they're helpful in keeping our codebase clean.
Rules reference: https://eslint.org/docs/latest/rules
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1396"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Add more ESLint rules

.github/workflows/merge-pro.yml
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/711
This is how our automated PR will now look https://github.com/tiny-pilot/tinypilot-pro/pull/929
---
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1425"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Reference the original community PR in auto Pro-PR

.circleci/continue_config.yml, bundler/bundle/install, get-tinypilot.sh, scripts/install-bundle
Resolves https://github.com/tiny-pilot/tinypilot/issues/1462
You can test this PR's install script and bundle via:
```bash
curl \
--silent \
--show-error \
https://raw.githubusercontent.com/tiny-pilot/tinypilot/aca37b26108c7fc7fc24fad48890734859fe9221/get-tinypilot.sh | \
bash -
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1464"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Place temporary install files within RAMdisk

CONTRIBUTING.md, requirements.txt
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1528"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Document how we upgrade pip packages

app/static/js/app.js, app/templates/custom-elements/menu-bar.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1673
https://github.com/tiny-pilot/tinypilot/assets/6730025/27a4b1ed-b104-4151-a391-9c7c1468101b
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1675"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Add "Pro" stub for Static IP feature

e2e/about.spec.js
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1136
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1682"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Add e2e test to check for broken license page links

e2e/about.spec.js
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1808"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Go to pages in parallel

get-tinypilot.sh
Related https://github.com/tiny-pilot/gatekeeper/issues/278
This PR backports the relevant changes to `get-tinypilot-pro.sh` (introduced by https://github.com/tiny-pilot/gatekeeper/pull/295) back into `get-tinypilot.sh`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1877"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
=> Backport changes from get-tinypilot-pro.sh
