tiny-pilot/tinypilot

- app/hid.py
- app/main.py
Writes to HID can fail if the USB cable is disconnected, so doing it in a separate thread avoids locking up the entire app.
Fixes #47
> Write to HID interface asynchronously

- app/hid.py
- app/js_to_hid.py
- app/main.py
- app/static/js/app.js
By default, JavaScript continuously generates onKeyDown events as long as the user holds down a key. This is fine for most keys, as holding down a key should be the same as repeatedly pushing a key. For modifier keys like Shift + Ctrl + Alt + Meta/OS, it yields unexpected behavior, like Windows triggering StickyKeys.
This fix adds special casing for modifier keys so that they don't trigger multiple key presses when held down.
Fixes #60
> Don't treat a hold of modifier key as multiple keystrokes

- README.md
- app/local_system.py
- app/main.py
Change CORS_ORIGIN to default to the local machine's hostname rather than assume that the machine is called 'tinypilot'.
Fixes #83
> Eliminate assumption that hostname is tinypilot

- quick-install
Ansible spews error messages if wheel isn't installed. They're benign, but it's cleaner if we just pre-install wheel.
> Adding wheel install to the quick-install script

- README.md
- app/main.py
Retrying this change. The first time (#98), I incorrectly applied the cors_allowed_origins parameter.
> Allow wildcard origin for CORS requests to socket.io routes (re-try)

- app/static/js/app.js
This fixes an issue where the key history area would expand as the user types keys even if they had disabled key history. The keys wouldn't display, but the empty space expanding was distracting/confusing.
Fixes #103
> Prevent history area from expanding when history is disabled

- quick-install
On non-Raspbian Debian systems like DietPi, we should check that all the apt packages are available to run the Ansible environment.
> Ensure all apt packages are installed for Ansible

- scripts/usb-gadget/README.md
- scripts/usb-gadget/init-usb-gadget
Moving it from its original location at https://github.com/mtlynch/ansible-role-tinypilot/blob/a087dbdab33d2f8c2c8e0ed45fa6da063988f9d2/files/enable-rpi-hid because it's tightly bound with the application and should live with the app code.
> Add init-usb-gadget script

- README.md
- app/hid.py
- app/main.py
Refactoring the code to get away from the language of HID as synonymous with keyboard. Mice are also HIDs but operate differently, so we should separate the concept of an HID from the concept of a keyboard.
> Relax assumption that keyboard == HID

- .circleci/config.yml
The quick-install script handles this internally as of #124
> Remove apt update from CI

- app/static/js/app.js
- app/templates/index.html
Unsure on approach to UI changes, but wanted to add support for debugging [Linux servers in known hung states](https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html) remotely.
This addresses feature request: https://github.com/mtlynch/tinypilot/issues/149
Might be worth integrating this into the nav bar better, so other keys (like PrintScr for Windows hosts) can be also added.
> Added SysRq key support for working with hung Linux machines remotely.

- scripts/usb-gadget/init-usb-gadget
The init script will eventually support more than one USB gadget function, so this makes the keyboard function explicit as its own function.
Related: #125
> Rename FUNCTIONS_DIR to KEYBOARD_FUNCTIONS_DIR

- app/js_to_hid.py
- app/main.py
- app/static/js/app.js
The previous mechanism assumed that the server always processed keystrokes in order, and it could go out of state when many keystrokes were sent in quick succession.
This switches to a more robust method where the client includes a unique identifier with each keystroke it sends to the server, and the server sends the ID back so that the client knows which response corresponds to which keystroke.
> Switch to a more robust system for tracking keystroke success

- app/main.py
- app/static/css/style.css
- app/static/js/app.js
- app/templates/components/connection-indicator.html
- app/templates/index.html
Rewrite the connection indicator in the navbar as an HTML custom element. In the process, I moved the error reason from a dialog box to the tooltip that displays when the user hovers over a "disconnected" indicator.
> Refactor connection indicator into custom element

- app/templates/components/content-tooltip.html
I accidentally left it in when copy/pasting the starting code from connection-indicator.
> Remove cruft from content-tooltip

- app/request_parsers/mouse_event.py
- app/tests/request_parsers/test_mouse_event.py
If a number gets sent as `0` (as opposed to `0.0`), the variable ends up as integer.
> Fix edge-case where numbers get parsed as integer

- app/templates/custom-elements/shutdown-dialog.html
click event broke on your commit (mtlynch#206), also disabled text select for the shut down modal.
I had to move the event out of the constructor, click events were coming from <shutdown-dialog>
> Fix overlay click out and add no select

- app/static/js/app.js
You are blocking mouse down and up, why not also block mouse events when connectedToServer=false.
> Block mouse events when not connected to server

- app/templates/custom-elements/shutdown-dialog.html
We're not doing anything with the change events, so we don't need to observe.
> Remove observedAttributes from shutdown-dialog

- app/static/js/app.js
Firefox still have ghost image when drag within tinypilot web UI.
This PR added listener to prevent default behavior on dragstart / drop on the parent remoteScreenDiv. This is what I found work most effectively.
> Prevent drag and drop on Firefox

- dev-scripts/serve-dev
dev-scripts/serve-dev serves TinyPilot in dev mode where it does not attempt to write to any HID interface.
> Add serve-dev convenience script

- app/templates/custom-elements/remote-screen.html
Because remote-screen registers an event handler outside of itself, we need to do some extra work to make sure we're not leaving around dangling references:
https://open-wc.org/faq/events.html#on-elements-outside-of-your-element
> Clean up event handler on window.resize

- app/static/js/app.js
- app/templates/custom-elements/shutdown-wait.html
Add a 30 second timer to change the message in the dialog and hide the spinner. Message will only change if the shutdown-wait dialog is still open. That last part might not be necessary since there really is no way to close it. Also this does not disable the socket client, if we are able to reconnect to the tiny pilot device the website will reload.
Fixes #224
> Fix Shutdown Wait - Mark Complete

- app/hid/keyboard.py
If we do them as separate writes and the second write fails, we end up in a situation where the key gets stuck pressed down.
> Consolidate key press and release writes to HID interface

- app/hid/write.py
Reverts mtlynch/tinypilot#251
We don't actually need to do O_NONBLOCK, as it will time out normally.
> Revert "Add a comment explaining why we open the HID interface as O_NONBLOCK"

- app/hid/write.py
Fixes 'Resource temporarily unavailable' exceptions when writing too quickly to the hid interface
> Fix write exception 'Resource temporarily unavailable'

- app/hid/write.py
I initially switched to os.open because I thought we needed to O_NONBLOCK flag, but given that it's unnecessary, we can go back to the regular file open API.
> Use regular open() function to write to the HID interface

- app/hid/write.py
I found new scenarios where the write can hang, which locks up the main server process. This change switches back to asynchronous writes, but instead of doing them in separate threads like we did before (prior to 73e3fb9), do them in separate processes so that we can kill zombie processes.
> Switch back to async writes to HID interface

- app/main.py
- app/static/js/app.js
I didn't realize we can just handle it in the .emit() response parameter.
> Drop keystroke-received socket event

- app/main.py
- app/request_parsers/keystroke.py
- app/static/js/app.js
- app/tests/request_parsers/test_keystroke.py
Using socket.io's callbacks, we don't really need to track keystroke IDs, so this removes them.
> Refactor out keystrokeId

- app/static/js/app.js
- app/templates/custom-elements/remote-screen.html
- app/templates/index.html
Fixes #46
Re-do of #223, which had to be rolled back due to a regression
> Add support for on-screen keyboard on mobile devices

- app/static/css/keyboard-panel.css
- app/static/js/app.js
Hiding the history now frees up that 90px of screen real-estate it was using. This helps keep the modifier key buttons in view by preventing overflow.
> Shrink History

- app/templates/index.html
Fix `Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.` and `The key "scalable" is not recognized and ignored.`
Note: The `user-scalable` disabled browser zoom on mobile. You may or may not want that, it is up to you.
> Fix Error parsing viewport meta content

- app/templates/custom-elements/remote-screen.html
Adjust the CSS rules for the remote screen image so that its margins reduce the smaller the screen is.
> Expand remote screen real estate when browser window is small

- app/static/js/app.js
- app/static/js/keycodes.js
- app/templates/index.html
This avoids polluting the global namespace and makes explicit which functions we want to export.
> Switching keycodes.js and app.js to ES6 modules

- app/static/js/app.js
- app/static/js/settings.js
When the user changes the screen cursor or 'show history' setting, these changes will now persist across browser sessions.
Fixes #274
> Persist user settings to browser local storage

- app/templates/custom-elements/remote-screen.html
Fix Mobile scroll down when keyboard is opened.
> Move input to top to prevent scroll down on mobile when keyboard is activated.

- app/static/js/app.js
- app/templates/components/keyboard-panel.html
Previously, the buttons in the web UI allowed the user to simulate holding a modifier key on the next keypress, but there was no way to send, for example, the OS keypress on its own. This change allows users to double-click the modifier key buttons to simulate a keypress of that particular key.
Fixes #37
> Support sending modifiers immediately with double click

- app/js_to_hid.py
- app/request_parsers/keystroke.py
- app/tests/request_parsers/test_keystroke.py
- app/tests/test_js_to_hid.py
Initially, TinyPilot assumed that all modifier key presses were left keys, but there are some devices where left vs. right modifier keys make a difference.
> Add support for right modifier keys

- app/templates/index.html
Setting user-scalable=no has the potential to create accessibility issues for users who need to zoom. Reverting this tag back to the standard, common value.
> Revert the meta viewport tag to one that's more standard

- app/templates/custom-elements/remote-screen.html
In some cases, the call fails when the 'this' reference is not set, so move the function out of the class context so that it always is defined.
> Fix bad reference to normalizeWheelDelta

- app/js_to_hid.py
It was mapped incorrectly for Firefox. It looks like it accidentally got garbled in the churn related to #235
> Fix JavaScript keycode for minus sign

- quick-install
This is a workaround from a very early version of TinyPilot when it was known as KVM Pi. At this point, it's unlikely that any users are running a version of TinyPilot that require this workaround, so we're removing it.
> Remove workaround for legacy KVM Pi Nginx config

- quick-install
Previously, we relied on ansible-role-tinypilot to set default settings for uStreamer, but this isn't very flexible. Instead, we're moving the defaults here so that ansible-role-tinypilot does not set any of its own uStreamer options and instead leaves those decisions to higher-level clients, like this installer.
> Set install options in the quick-install script

- quick-install
The ustreamer_capture_device install variable should take precedence over settings in /home/ustreamer/config.yml. If there's an explicit ustreamer_capture_device value, we should use that setting and only read the config file if there's no explicit value set for ustreamer_capture_device.
> Make ustreamer_capture_device take precedence over config file

- app/static/js/app.js
Previously we were hiding it from the keystroke history, but we may as well show it. It's not worth adding special rules for meta.
> Display keypress for meta key

- app/templates/custom-elements/key.html
- app/templates/custom-elements/on-screen-keyboard.html
Adds is- prefix to boolean properties to eliminate ambiguity about what type of value they store.
> Adjust property names in on screen keyboard

- dev-scripts/dump-logs
Sometimes users have support issues that are hard to diagnose without seeing the configurations they're running, so this adds the systemd config files to the dump-logs output.
> Include systemd configs in dump-logs

- app/templates/custom-elements/on-screen-keyboard.html
The Meta keys were incorrectly assigned to 102, which is the numpad 6 button.
> Fix keycodes for meta keys on on-screen keyboard

- app/templates/custom-elements/key.html
- app/templates/custom-elements/on-screen-keyboard.html
To avoid passing more data than necessary in the key click event, pass the explicit values we care about.
> Communicate keyclick details explicitly

- .github/pull_request_template.md
Add a link to "How to Make Your Code Reviewer Fall in Love with You" to the Github PR template to clarify good practices for submitting PRs.
> Add guide to GitHub PR template

- app/static/js/app.js
- app/templates/custom-elements/on-screen-keyboard.html
Previously, the on-screen keyboard never distinguished between left or right alt keys being pressed, but on certain keyboard layouts, the right alt is treated as AltGraph and has special meaning.
This change causes pressing the right alt key on the on-screen keyboard to set altGraphKey: true in the socket.io message to the backend, so that the backend translates it properly as a right alt modifier.
The behavior is not perfect in that it will treat holding the right alt key the same as holding both alt keys at once, but hopefully this moves us closer to a complete solution.
Fixes #350
> Support altGraph key on on-screen keyboard

- app/socket_api.py
- app/static/js/keystrokes.js
Fix a code path where the backend wasn't setting the success property of the response.
Adjust the JS code so that it doesn't crash when the success property is missing.
> Ensure socket API communicates success robustly

- app/static/js/app.js
- app/templates/custom-elements/on-screen-keyboard.html
We eventually need to move to a system where we track orientation of all modifier keys, but as a stopgap for now, keep the left alt and right alt modifiers separate on the on-screen keyboard.
> Separate left alt from right alt on on-screen keyboard

- requirements.txt
4.3.0 had a bug where it would upgrade to any version of python-socketio>=4.3.0. The issue is that python-socketio 5.x is incompatible with clients using JavaScript Socket.IO versions 1.x and 2.x, so it would upgrade to the latest version of python-socketio and break existing clients. This was fixed in:
https://github.com/miguelgrinberg/Flask-SocketIO/commit/59740d3eb50395f44cfb786b85215b4ec9b795e9#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
See also: https://github.com/miguelgrinberg/python-socketio/issues/578
See also: https://github.com/mtlynch/tinypilot/issues/368#issuecomment-742316061
> Upgrade Flask-SocketIO to 4.3.2

- app/templates/components/paste-overlay.html
Paste only works if the target system has en-US or en-GB keyboard layout, so this change adds a note to the paste overlay letting the user know.
It also changes CSS to make the caret a little less distracting.
> Add a note to paste overlay about keyboard layout requirements

- app/main.py
The default timeout is 1 hour, which can cause requests to fail if the page was loaded too long ago. Changing to None makes it last the duration of the session. The risk of CSRF attacks in TinyPilot is low, so we can afford to err on the side of usability.
> Eliminate time limit for CSRF tokens

- quick-install
Upgrades are slow now partially because we throw away the installer's virtualenv and recreate it from scratch. If we keep a permanent updater directory alongside the actual app, we can upgrade faster.
> Use permanent installer directory

- quick-install
We're transitioning away from installing roles implicitly through meta/main.yml, as it doesn't allow us to apply any logic before the install of dependent roles. If we install via the requirements.yml, we can choose when in the role we want to pull in the parent roles and add more sophisticated logic to them instead of installing them right off the bat with the default variable assignments.
> Install ansible role requirements through requirements.yml

- quick-install
quick-install depends directly on git as of 7c4aecb, so the installer should make sure that git is installed already.
Fixes #387
> Install git during quick-install script

- app/static/css/navbar.css
This doesn't change the UI, but it simplifies the CSS rules to keep the buttons in the navbar white.
> Fix anchor tag colors in navbar

- quick-install
Otherwise, only the outer installer directory is owned by the current user, while the contents may not be.
> Recursively chown installer directory

- app/api.py
- app/git.py
- app/update.py
- quick-install
- scripts/upgrade
The goal is to create three new endpoints that will later be used to update TinyPilot through the web UI:
* /version
* /latestRelease
* /update
This also removes the `scripts/upgrade` file from this repository (it currently resides in https://github.com/mtlynch/ansible-role-tinypilot).
It doesn't _actually_ remove the file but rather point to the user that the script location has changed.
This addresses the backend part of  #91.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/407)
> Create new "update" API endpoints

- README.md
In #407, we moved the update script to /opt/tinypilot-privileged/update, so this change updates the README to match.
> Rewrite update instructions in README

- README.md
Non-root users can't execute the update script, so they need to call sudo first.
> Add sudo to the update documentation

- quick-install
If a user follows old update instructions, they might accidentally downgrade the Pro version of TinyPilot to the free version. This adds a prompt to the installer to confirm that the user really wants to do that.
Fixes #412
> Prevent user from accidentally downgrading from TinyPilot Pro

- quick-install
Apparently the read -p command doesn't work when we're piping text into a bash interpreter, so this switches to an environment variable approach.
> Require user set an environment variable to downgrade from Pro

- README.md
- quick-install
- scripts/upgrade
If we break it, we can no longer give users a single command to update that will work regardless of their version of TinyPilot.
> Make the upgrade script work again for backwards compatibility

- app/api.py
Previously, we were returning HTTP 500 for any application error, but that makes it harder to write frontend code that wants to read the 'error' field of the response.
All of the frontend REST code checks the success result anyway, so we can rely on that instead of the HTTP error code and reserve HTTP error codes for uncaught exceptions that really surprise the app.
> Return HTTP 200 for application-level errors

- app/static/js/app.js
The word 'device' should be lowercase.
> Fix text in shutdown dialog

- app/static/js/shutdown.js
There's a bug in the handling of the fetch request because it attempts to resolve the Promise as success, but the next stage rejects it for not having the success parameter explicitly set in the response body. This updates it to add a fake success message becaues 502 almost certainly means shutting down the server worked.
> Make a fake success message when shutdown returns 502

- app/templates/custom-elements/shutdown-dialog.html
This fixes a bug in the logic flow. Previously, both restart and shutdown kicked off a 30 second timer to announce a shutdown is complete. The correct behavior is for restart to spin forever until it detects the server's websocket connection has been reestablished, and the shutdown flow should assume the server is shut down after 30 seconds.
> Only do a 30s countdown during shutdown, not restart

- dev-scripts/dump-logs
Closes https://github.com/mtlynch/tinypilot/issues/426.
Changes `dump-logs` to mimic the behavior of [`scripts/upgrade`](https://github.com/mtlynch/tinypilot/blob/e54c3bfa7a8f5ca815e9d3f804e0ce06944eb244/scripts/upgrade) in calling its replacement in `/opt/tinypilot-privileged/`.
> Change dump-logs to just call new script

- dev-scripts/check-trailing-whitespace
On macOS the functionality of the `--dereference-recursive` flag is replaced by `-R -S`; updated to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/434)
> Update check-trailing-whitespace to work on macOS

- app/api.py
- app/debug_logs.py
Closes https://github.com/mtlynch/tinypilot/issues/427.
Adds an API endpoint, `GET /api/debugLots`, that calls `collect-debug-logs` and returns its output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/436)
> Add GET /api/debugLogs endpoint

- quick-install
It looks like something changed in one of ansible's indirect dependencies recently, so now when we try to install Ansible, it fails due to a missing Rust compiler.
This fixes the issue by pinning ansible's indirect dependencies to their exact versions.
> Pinning indirect dependencies of quick-install environment

- .vscode/settings.json
4 spaces is what the style guide specifies and how YAPF formats:
https://google.github.io/styleguide/pyguide.html#34-indentation
> Update VS Code settings for default Python tab size

- app/js_to_hid.py
MacOS with an English/International keyboard sends its command keys as OSLeft and OSRight instead of MetaLeft / MetaRight. This adds support for those keys so that TinyPilot treats them the same as MetaLeft and MetaRight.
Fixes #498
> Add support for OSLeft and OSRight keycodes

- app/js_to_hid.py
- app/js_to_hid_test.py
This refines the special-casing so that we only do it in limited circumstances.
> Tweak logic of JS to HID key remapping

- app/debug_logs.py
- app/request_parsers/keystroke.py
- app/request_parsers/keystroke_test.py
- app/request_parsers/mouse_event.py
- app/request_parsers/mouse_event_test.py
>Libraries or packages may define their own exceptions. When doing so they must inherit from an existing exception class. Exception names should end in Error and should not introduce stutter (foo.FooError).
https://google.github.io/styleguide/pyguide.html#24-exceptions
> Fix names of custom exceptions to match style guide

- quick-install
Otherwise, ansible uses the cached version regardless of whether the remote has updated or if the local version doesn't match the requirement.
> Add --force to ansible-galaxy install

- quick-install
This will offer a cleaner way for users to persist settings across updates.
> Add support for a TinyPilot Ansible vars file in quick-install 

- app/api.py
- app/request_parsers/hostname.py
- app/request_parsers/validators/hostname.py
- app/request_parsers/validators/hostname_test.py
[PR #433](https://github.com/mtlynch/tinypilot/issues/433) had introduced the backend endpoints for changing the device hostname. It didn’t implement the rule, however, that the hostname must not be `localhost`. This is fixed here.
Also, the wording of the “bad request” error message was slightly adjusted to make it sound a bit less techncical. The message is intended to be displayed as is [in the frontend](https://github.com/mtlynch/tinypilot/pull/521).
> Fix hostname validation in backend: reject `localhost` as value

- app/templates/custom-elements/update-dialog.html
Tiny fix in the polling mechanism of the update dialog: when using [`String.prototype.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf) in JavaScript to find a substring, the result should always be compared against `-1` to check for absence. If the search term appears at the beginning of the string (like in this case with “NetworkError”) then `indexOf` returns `0` which evaluates to `false`.
Either one can do `error.message.indexOf("NetworkError") !== -1` or – better, since more expressive – `error.message.includes("NetworkError")`, which I have changed it to here.
> Fix detection of network errors during polling

- app/static/js/util/poll.js
- app/templates/custom-elements/update-dialog.html
`update-dialog.html` currently contains a `poll` function that “watches” a Promise until it resolves to a desired result. I’d like to reuse this polling utility in https://github.com/mtlynch/tinypilot/pull/521, therefore it gets extracted in this PR here.
Apart from whitespace changes (and the JSdoc), the code relocation is verbatim.
I deliberately placed it inside a `util` folder, since I think it makes sense to separate domain-specific code from generic utilities.
> Frontend: Extract polling utility in order to be able to reuse it

- app/debug_logs.py
Otherwise, it executes as the tinypilot user which doesn't have permissions to access all logs.
> Add sudo to the call to collect-debug-logs

- app/hostname.py
Similarly to https://github.com/mtlynch/tinypilot/commit/778d3dadb86e641eb270d376716ffed58e6c3316 the `change-hostname` script also has to be executed through `sudo`, because it needs to write system files, which it needs root permission for.
(Screenshot from real TinyPilot device running on a Pi; in the dev environment it might not be apparent if you execute the server via a root user.)
> Add sudo to the call to the `change-hostname` script

- README.md
We're (most likely) going to use it for hosting debug log uploads.
> Add litestream to acknowledgments

- app/api.py
- app/static/js/app.js
- app/static/js/controllers.js
- app/templates/components/navbar.html
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/index.html
This PR is the third and last part of the [feature to change TinyPilot’s hostname via the web UI](https://github.com/mtlynch/tinypilot/issues/433) and adds the frontend pieces.
~The PR should be feature-complete, but it’s nevertheless tentative because I want to look at it again with a fresh pair of eyes. There are a couple of things to discuss, though, so I was hoping that you (@mtlynch) could take a first look already and give me some feedback.~
~I also am unable to do any “real-life” acceptance testing currently, because I don’t have a Pi setup for development yet, which makes me feel a bit uncomfortable…~ *(I got around to doing some testing “for real” now, see comment below.)*
I’m not sure what level of knowledge to expect from the end user, so the wording in the popup might have to …
> Add frontend for changing the device hostname

- app/static/js/util/poll.js
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/update-dialog.html
This PR addresses / fixes https://github.com/mtlynch/tinypilot/issues/531. It’s not a direct fix, because in my opinion the polling mechanism should timeout *in general* and not just due to network errors. I think a user interface should never hang forever without giving indication that there might be a problem after a reasonable amount of time elapsed.
- I simplified the logic in `update-dialog.html`. I hope that was not too much. Happy to change it back.
- I moved the `validate(result)` call into the `try` block. I know that you prefer to keep the `try` block slim, however, `null` could be a valid response (in theory) so if it’s outside the `try` we cannot distinguish this case without introducing additional helper variables.
- The error message in `update-dialog.html` could potentially …
> Make polling mechanism more reliable and more generic (frontend)

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/connection-indicator.html
- app/templates/custom-elements/custom-footer.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/menubar.html
- app/templates/index.html
- dev-scripts/check-frontend-format
There was a bug in the CI config for Prettier, so it was failing to format files in app/templates. This fixes the formatting and corrects the bug in the CI config.
This is a pure refactoring change. I just ran Prettier over the files that it was missing, so this should have no functional effects.
The one exception is that I fixed an unclosed HTML tag in app/templates/custom-elements/connection-indicator.html.
> Fix formatting in templates

- app/static/css/style.css
These colours were taken over from the redesign proposal in https://github.com/mtlynch/tinypilot/pull/548.
They are not used yet, so this PR doesn’t have any observable effect other than making these variables available for subsequent PRs to build on.
> Introduce CSS colour variables

- app/static/css/button.css
- app/static/css/keyboard-panel.css
- app/static/css/style.css
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/connection-indicator.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/key-history-card.html
- app/templates/custom-elements/menubar.html
- app/templates/custom-elements/progress-spinner.html
- app/templates/custom-elements/remote-screen.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
This PR (part of https://github.com/mtlynch/tinypilot/pull/548) replaces all inlined colour definitions with the ones centrally defined in `style.css` (#550). The only inline colours left are gray tones. This is okay, since it’s often hard to impossible to really unify all gray shades.
`screen-wrapper` doesn’t need his own bg colour, since the `body` bg is defined as `--brand-creme-light`.
> Replace all inline colour definitions by the central ones

- app/static/css/button.css
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/shutdown-dialog.html
The hostname panel used to repeat the button definition of the success button for no good reason. Also, `btn-danger` should live in `button.css`.
> Refactoring: don’t repeat button definitions, use the centrally defined ones

- app/static/css/button.css
- app/static/css/style.css
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/connection-indicator.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/key-history-card.html
- app/templates/custom-elements/menubar.html
- app/templates/index.html
As discussed in https://github.com/mtlynch/tinypilot/pull/548 we want to change to a sans-serif typeface to create a more professional look and feel. Therefore we switch to the font “Overpass” in this PR, which also happens to come with a matching monospace variant.
Some CSS had to be adjusted to account for the different spacing behaviour of the new font. The size of the header bar was slimmed down to `45px` to make the look consistent.
- `*` is not necessary for declaring a font, the font properties get inherited from the root element. (Except for form elements, see `button.css`.) It’s generally better to inherit font properties if possible, rather than targeting all elements.
- I changed the pattern for indicating the selected mouse cursor from “blue background colour” to a “✓” …
> Change font to sans-serif

- app/templates/styleguide.html
- app/views.py
As discussed in https://github.com/mtlynch/tinypilot/pull/548 it can be helpful to have an ongoing collection of all visual patterns and elements that are used across the app. This helps in the longer run to keep the UI consistent, and it also promotes reusability of UI components.
I made good experiences working with style guides, even on smaller projects. If it doesn’t turn out to be helpful for us, we can ditch it anytime.
The style guide is only shown when `debug` is turned on.
> Setup style guide for internal usage

- app/templates/custom-elements/connection-indicator.html
That one slipped through. (Red icon was not shown due to this.)
> Fix connection indicator in status bar

- app/socket_api.py
I originally added wildcard support so that users could access TinyPilot from addressess like http://tinypilot or http://10.0.0.123 and it was breaking when CORS was hardcoded to a specific address. But the better fix is to just remove the CORS handling altogether and accept Flask-SocketIO's default behavior of same-origin, which will work regardless of whether the user accesses by IP, hostname, or even a remapped hostname that the server doesn't know about.
Fixes #99
> Remove CORS workaround for Flask-SocketIO

- app/templates/custom-elements/menubar.html
Tiny refactoring to give clearer indication of the purpose, i.e. that this is a callback to inform the outside about an internal state change. This is inline with the naming of `showKeyboardCallback`, introduced in https://github.com/mtlynch/tinypilot/pull/560.
> Improve variable name

- app/static/js/app.js
- app/static/js/settings.js
- app/templates/custom-elements/menubar.html
The virtual keyboard is likely not used super frequently, so people might prefer to hide it. This PR adds a menu item with which you can show or hide the entire keyboard panel.
For now the default is to show the keyboard, as it used to be before. The reason is mainly that we don’t have the status bar yet, so the keystroke history is the only place that gives visual feedback about input events. Once we have migrated this indicator to the status bar, we can consider changing the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/560)
> Give users the option to toggle virtual keyboard

- app/static/js/app.js
- app/templates/custom-elements/menubar.html
As discussed in #560 the menu bar shouldn’t access the DOM directly but rather emit events to let `app.js` handle them. As a consequence, the internal setup of the menu becomes more straightforward and allows for some simplification.
No functional changes have been made.
Side note: if you have a better thought about the event names, I’m keen to hear. What I aimed for was this: a) use past tense, b) use active language (verb), c) make clear that the events are just user requests triggered through the UI, but not an actual state change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/564)
> Refactor control flow inside menu-bar component

- CONTRIBUTING.md
- dev-scripts/enable-mock-scripts
- dev-scripts/mock-scripts/README.md
- dev-scripts/mock-scripts/change-hostname
- dev-scripts/mock-scripts/collect-debug-logs
This enables TinyPilot developers to mock out two privileged functions during development:
* Change hostname
* Collect debug logs
Once the developer enables mock scripts on their system, they can use these two features and have it work (sort of) like it works on a real device.
This still leaves a few functions unmocked:
* Shutdown/restart (because we call those by absolute path to system scripts, we can't mock them out)
* Update: The update logic is pretty complex and involves launching a systemd process, so it's non-trivial to mock this out.
See #501
> Add mock scripts for development

- app/static/css/style.css
- app/static/js/app.js
- app/templates/custom-elements/connection-indicator.html
- app/templates/custom-elements/content-tooltip.html
- app/templates/custom-elements/menubar.html
- app/templates/custom-elements/status-bar.html
- app/templates/index.html
As discussed in [the redesign proposal](https://github.com/tiny-pilot/tinypilot-pro/issues/53) this PR introduces a status bar at the bottom of the screen.
Equivalently to the menu bar, it’s also hovering on top of everything else in a fixed position. Currently it only houses the connection indicator, but it will soon also contain the indicator for user input events.
- It’s the same question all over again how to make child components accessible in the code (in React too), i.e. whether either to just expose them directly (at the expense of violating Demeter’s law and encapsulation), or to wrap them up explicitly (at the expense of writing trivial decorator code). I eventually concluded that it’s okay to expose the connection indicator to the outside of the status bar, since I think of the …
> Introduce status bar at the bottom

- .circleci/config.yml
- .shellcheckrc
- CONTRIBUTING.md
- dev-scripts/build
- dev-scripts/check-bash
- dev-scripts/check-trailing-newline
- dev-scripts/check-trailing-whitespace
- e2e/docker-test
- e2e/test
- quick-install
- scripts/upgrade
Added a script to find all the bash scripts in this project and run static analysis on them.
Added that script as a Circle CI job.
I excluded all the problems that ShellCheck picked up in this project (by excluding them in command-line arguments).
1. I wasn't sure if it's something we would like to fix in this PR.
2. I'm not sure each "problem" is worth fixing as it would expand nifty one-liners into multiple lines. A decision needs to be made on which error codes we care about. Here are the list of issues that it picked up: 
```bash
In ./dev-scripts/check-trailing-whitespace line 15:
$(git ls-files | xargs); then
^---------------------^ SC2046: Quote this to prevent word splitting.
In ./dev-scripts/check-bash line 16:
-exec bash -c 'head -n 1 {} | grep --quiet "#!/bin/bash"' \; \
^-- …
```
> Add ShellCheck to Circle CI config.

- app/templates/index.html
- app/views.py
This helps the user identify the TinyPilot window if they have multiple TinyPilot devices.
Fixes #577
> Display device hostname in page title

- app/socket_api.py
Based on the [fix applied to the nginx config](https://github.com/mtlynch/ansible-role-tinypilot/pull/113), we can now remove the wildcard from the CORS allowed origins.
Fixes #99
> Remove wildcard from CORS allowed origins.

- app/templates/custom-elements/error-dialog.html
- app/templates/styleguide.html
- app/views.py
Having the error dialog in the style guide is helpful because it's an easy way to preview the error dialog without forcing an error state in the app.
> Add error dialog back to the style guide

- app/static/css/style.css
- app/static/js/app.js
- app/static/js/overlays.js
- app/static/js/paste.js
- app/templates/custom-elements/error-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/index.html
- app/templates/styleguide.html
- app/views.py
Addresses https://github.com/mtlynch/tinypilot/issues/536 and introduces a custom overlay component that can be used for all dialog panels. The usage is demonstrated on the style guide page. I have also tested it out in the “real” app already, where it appears to work fine too.
- The `danger` variant already accounts for the to-be-introduced error panels, it’s basically a styling variation. (Analogous to `btn-danger`.)
- https://github.com/mtlynch/tinypilot/issues/583 is accounted for (but of course we must migrate first to close this issue).
- I deliberately did **not** take over the `user-select: none` directive that is present on the original overlays. Was there a specific reason why you did that initially?
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Introduce custom (reusable) overlay component

- app/templates/styleguide.html
The style guide is a good place to document implicit UI rules explicitly, e.g. how to word buttons or when to use the monospace font. I added a few more bits of info to round it out with what we have so far.
> Make style guide more complete

- app/static/js/app.js
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/index.html
- Wrap up the shutdown dialog into the new generic overlay and migrate all related code
- Introduce a `isShown()` method on the overlay (since `app.js` depends on that functionality)
- Use underscore prefix to indicate private visibility of methods
- The diff in the HTML is because I stripped the obsolete enclosing `<div>` which changed the indentation level
- I had to remove the “outside” click functionality unfortunately. We can consider to bring it back to the generic overlay, although I think it’s not strictly needed.
> Refactor shutdown dialog to use new overlay

- app/static/js/app.js
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/index.html
Same procedure as last year (https://github.com/mtlynch/tinypilot/pull/590)
Well, almost: I also had to remove the “custom” keystroke disabling and move the initialisation call to `app.js`. (The latter is now inline with how we do it for the other dialogs.)
> Migrate hostname overlay

- app/update.py
- scripts/update-service
The post-update check was treating the timestamp as the update completion time, but the update writer was only updating the timestamp at update start. As a result, TinyPilot would never see updates complete if they took longer than 3 minutes because 3 mins was the cutoff.
This relaxes the cutoff to 5 + 3 = 8 minutes and also adjusts the update logic so that it refreshes the timestamp at the end of the update.
> Adjust timing of update logic

- app/static/js/app.js
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/error-dialog.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/styleguide.html
This PR ensures that all error messages comply with the rules given in the style guide.
- Use “Title Case” for the title
- Display the technical error inside the “details” box
- Show an actionable, user-friendly message (for this PR the message is generic, as the error case itself is unspecific)
- Log to `console.error` centrally
- Streamline/cleanup the control flow a little bit
I’m not *super* happy with how the default error message fallback is implemented. Ideally I think we should have a central helper for generating the error data structure that we can import, to make the whole setup a bit less repetitive. I would hold off on further refactorings, though, until we have bundling and modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Revise user-facing error messages

- app/templates/custom-elements/error-dialog.html
Changes the overflow setting to 'auto' so that horizontal and vertical scrollbars show up only when necessary rather than automatically.
> Hide scrollbars in error details pane unless the text overflows

- app/templates/custom-elements/error-dialog.html
- app/templates/styleguide.html
You mentioned once that the details box is helpful so that people can make screenshots of the error message. For that purpose it might be good if the text never overflows horizontally, because then information would be missing in the screenshot. Of course, the text can still overflow vertically, but that probably happens less often and it’s less likely for people to miss (compared to horizontal overflow).
> Error details: break lines so that we never overflow horizontally

- app/api.py
- app/json_response.py
- app/main.py
Fixes https://github.com/mtlynch/tinypilot/issues/505 by introducing a “catch-all” exception handler that makes sure we always compose a valid JSON response and don’t accidentally return the Werkzeug HTML page or plain text. That practically means that internal server errors (`500`) or routing errors (`404`) will now yield a JSON response according to our convention.
Also eventually fixes https://github.com/tiny-pilot/tinypilot-pro/issues/53 (last remaining action item).
- I pulled out the factory functions to create flask responses, because I didn’t want to repeat them inline again in `main.py`.
- I took over the status code from the `HTTPException` (if applicable) or default to `500` respectively. This is inline with the previous behaviour, even though it’s not consistent with our own …
> Register default JSON error handler

- app/templates/index.html
- app/views.py
Refactor the page title prefix so that it's in views.py instead of index.html. In the Pro version, there are more views, so it's easier to share the logic if it's in views.py.
> Refactoring page title prefix logic

- README.md
- app/main.py
- dev-scripts/serve-dev
Listening on all interfaces is really only useful during development. In production, nginx forwards requests to TinyPilot, so TinyPilot doesn't need to listen on any non-localhost interface.
While I can't think of any security issues related to this, it's safer if we reduce the attack surface by listening only on on interfaces that are strictly required in production.
> Listen only on localhost by default

- app/api.py
- app/version.py
TinyPilot Pro and TinyPilot Community Edition use different logic to check the local and latest version. Abstracting it into a version module will lead to fewer merge conflicts when sharing code between the two repositories.
> Abstracting away concept of 'version'

- CONTRIBUTING.md
- README.md
They aren't really something an end-user should change. They are more useful to developers working on the code.
For end-users, the preferred way to change options is through the settings.yml file and advanced installation (linked to in the README).
Fixes #603
> Move documentation of environment variables to CONTRIBUTING.md

- app/main.py
- dev-scripts/serve-dev
I kept it in to facilitate development, but it's generating noise in the logs during updates when TinyPilot tries to reload as files change for the update. Now it's off by default, but the serve-dev script enables it for development.
> Disable hot reloading by default

- quick-install
Users now need add any extra/custom tinypilot config to a `/home/tinypilot/settings.yml` file.
(This PR is also needed to wrap up the [ansible side of the "Create convenience script for updating uStreamer settings" feature](https://github.com/mtlynch/ansible-role-ustreamer/pull/37#pullrequestreview-621681949))
1. I had reorder some of the code in the quick-install script in order to check & set variables in the `settings.yml` file.
2. When it comes editing the `settings.yml` file, I kept it simple by using grep to search for variables & echo to append default variables to the yaml file. I foolproof solution would have been to parse the yaml properly and export back to a file, but that would require adding extra dependencies to the project.
3. I wasn't sure what the prefered style is for …
> Deprecate TINYPILOT_INSTALL_VARS in quick-install script

- quick-install
Reverts mtlynch/tinypilot#630
Upgrading to 2.10.0 is actually more complicated than I thought:
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#upgrading-from-2-9-or-earlier-to-2-10
> Revert "Upgrade Ansible in installer to 2.10.0"

- app/static/js/app.js
- app/static/js/controllers.js
- app/templates/custom-elements/update-dialog.html
When we upgraded from socket.io protocol 2 to 3, it broke the check for whether a restart had completed because the frontend was still on protocol 2, and the backend had upgraded to protocol 3. The result was that the update screen spun forever because it was [waiting for onSocketConnect](https://github.com/mtlynch/tinypilot/blob/7a65a6c95d4ad926c041a63685e81981fbdf12f4/app/static/js/app.js#L117L122) to wake up and change the state. But because of the version incompatibility, `onSocketConnect` never executed.
We should rely on regular HTTP to check the status after an update so that we're not vulnerable to this sort of bug in the future.
Fixes #596
--- …
> Use HTTP instead of socket.io to detect when an update is complete

- quick-install
By default, creating a file with mktemp makes it rw only to owner. This means that after we chown to tinypilot, the ansible-playbook command (running as standard user) fails because it can't read the previously-created settings.yml file.
> Set tinypilot settings file to be world-readable

- app/hostname.py
The generic except block was introduced in https://github.com/mtlynch/tinypilot/pull/504, because a) Flask didn’t handle unhandled exceptions gracefully and b) we didn’t have the mock scripts yet. Both is obsolete by now, so it can eventually go away.
(I probably should have put a `todo` in the code… 👀 )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/637)
> Remove generic except block

- app/update.py
- app/update_result_reader.py
- app/update_result_reader_test.py
- app/update_test.py
- scripts/update-service
This refactors the update module to make it simpler, more testable, and better documented. This *should* be a pure refactoring that preserves all existing behavior.
The update component is important because failed updates are an especially poor user experience. There were previously no automated tests because of the difficulty of testing update logic, but I've broken up the module to mock out dependencies that were obstructing testing.
I'm planning to simplify the logic in a future PR (see #597), but I wanted to first create tests to lock in the existing behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/636)
> Refactor update module and add unit tests

- app/update_result.py
- app/update_result_reader_test.py
- app/update_result_test.py
- app/update_test.py
- scripts/update-service
We never read the field in produciton code, so it's just adding extra complexity. It's better to just assume that empty error string == success.
> Remove success member from update_result.Result

- README.md
- app/templates/custom-elements/menubar.html
We don't need to say 'change hostname' or 'view logs' because it's assumed that the user will be able to manage them.
> Make system menu options more concise

- app/request_parsers/hostname.py
I realized I just read the call to it and couldn't remember what the parameter meant without jumping to the function definition. We should make it obvious from the callsite.
> Clarify method call to parse_message

- app/update/settings.py
- app/update/settings_test.py
The update settings module had confusing naming and was awkward for callers to use because they had to directly open the settings file and pass it to the module. It wasn't so bad when there was just one caller, but it looks like we'll potentially have many callers, so it makes sense to make the calling semantics easier and more obvious.
Before: Callers were responsible for opening the update settings file and passing the file handle.
After: The settings module is responsible for managing the file handle. Callers don't have to know where the file is located.
Fixes #650
> Change semantics of update settings module

- app/update/settings.py
- app/update/settings_test.py
The previous implementation used an awkward way of storing the path to the update settings YAML file to facilitate testing.
@jdeanwallace pointed out a cleaner way to mock the value, so this changes the setting to a constant and uses the unittest.mock module to mock that constant in tests.
> Adjust file to update settings for cleaner mocks

- app/update/result.py
- app/update/result_reader_test.py
- app/update/result_test.py
- app/update/status.py
The previous implementation was inconsistent about what value the update status API returned for the error field. Through some code paths, it would return an empty string for the error field on success, and for other code paths, it returned null.
This changes the update modules so that they consistently use an error value of None/null to represent a successful update result.
> Use error=None to represent update success

- quick-install
We don't need to set this explicitly, as it's already uStreamer's default.
> Remove setting for default FPS in settings.yml

- app/update/result_store.py
- app/update/result_store_test.py
- app/update/status.py
- app/update/status_test.py
- scripts/update-service
It makes more sense for this module to handle both reading and writing persistent data about updates, and it makes it easier to test the logic.
> Change update result reader to update result store

- quick-install
We add default values to /home/tinypilot/settings.yml during quick-install when we detect the capture device *isn't* TC358743, but we should add defaults for TC358743 as well.
Previously, it worked fine without defaults because the ustreamer role loads those defaults internally:
https://github.com/mtlynch/ansible-role-ustreamer/blob/8de9de8358c46b181d517216a817fdcc0cd0ee84/tasks/provision_tc358743.yml#L53L60
The problem is that if we only want to run a subset of plays from the ustreamer role (like we do in /opt/tinypilot-privileged/update-video-settings), those values never load, so we need to persist them in the settings.yml file where we can access them instantly without running the full ustreamer Ansible role.
> Add default values for TC358743 during quick-install

- app/update/launcher.py
- app/update/launcher_test.py
- app/update/result.py
- app/update/result_store.py
- app/update/result_store_test.py
One of the most complicated aspects of the in-browser updates is recording state on the update despite the fact that the Flask server is stateless.
TinyPilot currently achieves this by writing an "update result file" at the end of each update. But there's complexity there because the server has to make sure that when the user requests status of an update, the server isn't checking an obsolete update file (e.g., the recently launched update hasn't written a file yet, so the only update result is from an update two weeks ago).
Currently, we solved this with timestamps, where we defined a time threshold of eight minutes. So, if the server found a result from more than eight minutes ago, it would assume it was irrelevant to the user's current request about update job status. That's a brittle …
> Clear previous update results before launching new update

- app/api.py
- app/request_parsers/errors.py
- app/request_parsers/validators/video_jpeg_quality.py
- app/request_parsers/validators/video_jpeg_quality_test.py
- app/request_parsers/video_jpeg_quality.py
- app/request_parsers/video_jpeg_quality_test.py
- app/static/js/controllers.js
- app/templates/custom-elements/video-settings-dialog.html
- app/update/settings.py
- app/video_settings.py
This PR adds "JPEG Quality" to the `video-settings-dialog` custom element. [Video demo](https://www.loom.com/share/8b5dc0a54c0746b19ee6ebcea11c4cf8).
This is a continuation of the work done in #629 of allowing video settings to be changed via the web UI.
This relies on https://github.com/mtlynch/ansible-role-ustreamer/pull/39 to be merged.
Fixes #448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/667)
> Change uStreamer jpeg quality from the web UI

- scripts/update-service
There was a bug in the error recording logic of update-service. Previously, if an error occurred during the try/catch, it was recorded in the update result's error field, but then the last line of the function overwrote any error with an empty string, erasing the record of the error.
This rewrites the logic so that each exit path generates its own update result object, so it's harder for values from one result to bleed into another code path.
This also changes the semantics of the success case so that error=None instead of error=''. In #659, we updated all instances of the error field to use error=None to represent success, but we missed the usage in update-service.
Fixes #665
> Fix result logic in update-service

- app/static/css/button.css
- app/templates/styleguide.html
Currently the button styles are only available on a `<button>` element. In order to make other elements look like a button, we need to introduce a separate CSS class.
Just fyi about the `button.btn-success { ... }`: it is a bit of an antipattern in CSS to restrict a class to a certain element. There is not really a benefit in doing this and it makes reusing the class harder. It can also be a problem when composing CSS classes, because `element.classname` takes precedence over just `.classname` in the hierarchy, so it’s harder to override.
For whatever reason we had `<button class="btn">` in the style guide. The class didn’t exist before, though, and it’s superfluous anyway.
> Make button styles reusable (`.btn` class)

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/progress-spinner.html
- app/templates/styleguide.html
In order to reuse the progress spinner in different layout contexts we have to refactor the CSS a little bit.
In this case I think it’s too arbitrary to hard-code specific variants, e.g. `size="large"` that would result in a fixed width of `1.8rem` or the like. Instead, it’s best if the caller can adjust the styling according to the context. That can be done through CSS variables. The usage is demonstrated in the style guide.
In the hostname dialog I had to wrap the spinner into a div, because it’s `inline-block` now – otherwise it would be placed in one line with the button there.
I also cleaned up the CSS a little bit.
> Make styling of progress spinner adjustable

- app/api.py
- app/json_response.py
- app/request_parsers/errors.py
- app/request_parsers/hostname.py
- app/static/js/controllers.js
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/error-dialog.html
We are currently using HTTP status code 200 all the way for API responses and rely on a custom JSON structure to distinguish an error from a success. (See also https://github.com/mtlynch/tinypilot/issues/506.)
This PR proposes a new internal convention for JSON responses:
- Rely on HTTP status code as the primary indicator whether a request succeeded or not. `2xx` is a success, anything else is treated as failure.
- Error responses follow a uniform pattern: `{ code: "…", message: "…" }`. The purpose of `code` is to allow us to handle specific cases programatically. (It’s currently the name of the error, but we might want to set it explicitly.)
- The frontend should be in charge of assembling any user-facing messages, because it’s the frontend’s responsibility how things are phrased or …
> Introduce new pattern for API responses (and migrate hostname feature)

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
Quick boy scout refactoring, I stumbled across these two places and noticed they weren’t inline with the style guide.
> Use title case and proper headlines in overlays

- app/git.py
If the TinyPilot has any commits or tags that conflict with the server, the server's version should override the device's.
This has caused issues in cases where we accidentally published conflicting release tags, but then device that saw the old release tag error out if they see the new one.
> Add --force to git fetch command

- app/static/js/controllers.js
Include context information when returning the error from `processJsonResponse`:
In this case we don’t have the original body anymore and we can’t easily retrieve it, because you can’t consume the response stream multiple times. I suppose it should be fine anyway, because that kind of error should be very rare.
> Frontend controller: Include original errors / texts when handling response errors

- app/api.py
- app/main.py
- app/static/js/controllers.js
~**Work-in-progress – feel free to disregard altogether for now.** It’s mostly done, but I still need to do some thorough testing. Will continue Tuesday at the latest.~
Addresses https://github.com/mtlynch/tinypilot/issues/506 and migrates all remaining endpoints to the new response scheme. No functional changes introduced.
I eventually decided to do the rest of the migration in one go, even though the changeset is more comprehensive now. I realised, however, that having both structures in parallel also causes complexity, so it’s suboptimal either way. Therefore I thought it was easier to just move forward and get it all done in one go.
One note about the pro repo: I didn’t delete the old functions in this PR yet, because then they would disappear in pro when merging from here. The pro …
> Migrate all API endpoints to new response structure

- app/api.py
- app/json_response.py
- app/main.py
- app/static/js/controllers.js
Complete the migration of the API responses:
- Rename `success2`→`success`
- Remove deprecated functions
- Keep a proxy version of `success2` and `error2`, otherwise it will break Pro upon merging.
> Remove deprecated functions

- app/templates/custom-elements/video-settings-dialog.html
* Make the sliders wider so that it's easier to pick precise values
* Rename video-jpeg-quality -> video-jpeg-quality-slider
* Rename video-fps -> video-fps-slider
* Adjust spacing to add some more whitespace between elements
* Fix alignment so that the sliders are vertically aligned with the text
> Tweak CSS on video settings

- app/static/js/app.js
- app/templates/custom-elements/debug-dialog.html
I noticed that we use a custom error handling in the debug logs, but actually we have a general mechanism for errors in overlays.
> Reuse generic error handling mechanism of overlay

- app/templates/custom-elements/debug-dialog.html
- app/templates/index.html
Based on https://github.com/mtlynch/tinypilot/pull/698, apply the changes to the debug logs dialog. ~(Waiting to be rebased.)~ Rebased.
> Debug Logs Overlay: redesign in-overlay buttons

- app/hid/keyboard.py
- app/hid/keyboard_test.py
- app/hid/write.py
`hid.keyboard.send_keystroke` was always releasing the key after it has been pressed. This is because a keycode is not actually set when a modifier is pressed on it's own. This stopped us from doing things like holding in the shift key and clicking with the mouse to highlight text. [Demo video](https://www.loom.com/share/8a4629a3a70f459d9869cd493e04289a).
Fixes #620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/692)
> Fix modifier keys that don't work in combination with mouse clicks.

- app/api.py
- app/static/js/controllers.js
- app/templates/custom-elements/update-dialog.html
[Demo video](https://www.loom.com/share/b87373a336a84996ab3c9fc04f08ea17).
1. Backend: Added an `updateError` field to the `/api/update` API endpoint response.
2. Fontend: Throw an error immediately when the `updateError` is not null.
Fixes #649
> Fail fast when an error occurs during an update.

- app/static/css/style.css
- app/templates/custom-elements/change-hostname-dialog.html
It’s useful to declare the styling of the input field globally, so that it’s always consistent. In the community version we only have one text input field (change hostname overlay), but in Pro we have more (security overlay and login screen), so I need it for that primarily (https://github.com/tiny-pilot/tinypilot-pro/pull/145).
While on it, I quickly tweaked the spacing between label and input field in the hostname overlay. I don’t know why I originally added `margin: 0 auto` there, that doesn’t make any sense since the elements are inline.
> Declare global style for textual input fields

- quick-install
The ansible-role-tinypilot-pro role depends on 3.3.2, so we have to keep hte two in sync.
> Upgrade cryptography dependency to 3.3.2

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/error-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/custom-elements/video-settings-dialog.html
- app/templates/styleguide.html
In order to avoid repetition in the dialogs we can (re-)use a centrally defined event class instead of implementing the same configuration in every dialog component.
I was considering to keep the internal `_close` methods, but ended up finding it more straightforward to dispatch the events right then and there. The class name of the event should be expressive enough and I find the control flow sufficiently easy to follow that way.
One note about `<debug-dialog>`: `_reset` is not needed on close, as the dialog is always initialised with `getLogs`, which will set the internal state to `logs-loading` as first thing, so the `null` state was never visible.
(Originated in https://github.com/mtlynch/tinypilot/pull/708.)
> (Re-)Use centrally defined event for closing dialogs

- app/static/js/app.js
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/error-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/custom-elements/video-settings-dialog.html
Introduce a new central event class for dialog failure: `DialogFailedEvent`.
- A failure always terminates the dialog, so it’s redundant to trigger the closing explicitly. That is supposed to be reflected in the name “failed”.
- I think the event classes are the best place to describe the parameters, because this is what we regularly see and use when developing.
- As discussed, showing the error dialog is still happening in `app.js` as it is now. Not super nice, but works. I kept the old `errorEvents` array to not break Pro upon merging. (There might be a conflict due to prettier formatting, though.)
- Probably hard to spot in the diff: there was a whitespace/grammar issue in [the hostname dialog](https://github.com/mtlynch/tinypilot/compare/dialog-error-events?expand=1#diff-12f4fd7d48da26 …
> (Re-)Use centrally defined event for dialog failures

- ARCHITECTURE.md
- CONTRIBUTING.md
- README.md
- quick-install
The role has moved from mtlynch/ansible-role-tinypilot to tiny-pilot/ansible-role-tinypilot, and we're no longer using Ansible Galaxy.
Related: https://github.com/mtlynch/ansible-role-tinypilot/pull/137
> Update URL for ansible-role-tinypilot

- app/static/css/icons.css
- app/templates/custom-elements/button-dropdown.html
- app/templates/styleguide.html
So far the dropdown button was custom in the virtual media overlay. In order to reuse it, this PR introduces it as standalone component.
- By using a slot, the component for opening/closing the dropdown can be completely customised. So it can be any button variant, but also other elements. The arrow icon is therefore separate, so that its exact styling/position can be controlled from the outside too.
- In contrast to before (in the virtual media dialog) the global event listeners are now only active when the dropdown is open. Before, they were registered all the time, which is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/tinypilot/721)
> Add standalone / reusable dropdown button

- app/templates/custom-elements/video-settings-dialog.html
[Video demo](https://www.loom.com/share/e72aab42ffea48788a845c8cbacfdf79).
> Alternatively, we could get the defaults when the dialog first loads and cache them so that we don't need to make a request at the moment the user hits the button.
I went with this solution 👆 
Fixes #710
> Preload default video settings to avoid screen flashing

- CONTRIBUTING.md
- README.md
- app/js_to_hid.py
- app/templates/custom-elements/menu-bar.html
- setup.py
I've moved tinypilot from mtlynch/tinypilot to tiny-pilot/tinypilot, so this makes all the URLs match the new location.
> Update URLs for new TinyPilot org

- .circleci/config.yml
Our end-to-end tests are costly, but not very rigorous, so they rarely (if ever) catch any failures, but they slow down our development workflow. This change skips the end-to-end tests on pull requests and limits them to the master branch.
This has the downside that we'll notice build failures later, but I think this happens so infrequently that it's not a problem. We can revert it later if it becomes a problem.
> Run end-to-end tests only on the master branch

- app/api.py
[Demo video](https://www.loom.com/share/2d637246c0244ac29695a8458f4f48d5).
If you update TinyPilot from a version before our [migration to conventional HTTP status codes](https://github.com/tiny-pilot/tinypilot/issues/506), the then outdated frontend code doesn't accept the newer api responses (i.e. missing `success` & `error` properties).
This PR adds the `success` & `error` properties back into the response to allow the older frontend code to continue with it's update. Specifically making `/restart`, `/update`, and `/status` API endpoints backwards compatible.
Fixes https://github.com/tiny-pilot/tinypilot-pro/issues/173
> Add backwards compatibility to the API to allow successful updates.

- app/js_to_hid.py
- app/js_to_hid_test.py
- app/request_parsers/keystroke.py
- app/request_parsers/keystroke_test.py
- app/static/js/app.js
- app/static/js/keyboardstate.js
- app/static/js/keycodes.js
- app/templates/custom-elements/on-screen-keyboard.html
As discussed in https://github.com/tiny-pilot/tinypilot-pro/issues/153 we want move client-specific oddities from the backend to the frontend. That leaves us with one canonical data structure to represent a keystroke, which we can reuse “as is” for the public API.
One note: I’m not sure it’s a good idea to rely on [`KeyboardEvent.metaKey`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) et al, but I think it’s probably better to always rely on the codes to figure out when it’s a modifier key. Otherwise we will always have the problem that we can’t tell apart left from right (or at least not without workarounds). Therefore, this PR would then also fix https://github.com/tiny-pilot/tinypilot/issues/364.
@mtlynch could you quickly look over this, please? It’s still …
> Refactor keystroke processing

- app/templates/custom-elements/on-screen-keyboard.html
Fixes https://github.com/tiny-pilot/tinypilot/issues/729.
(Screenshot to show that we are generating the same tuple of up/down events for physical space and virtual space key.)
> Virtual Keyboard: Send correct key code when pressing the space bar

- app/request_parsers/keystroke.py
- app/request_parsers/keystroke_test.py
As discussed in https://github.com/tiny-pilot/tinypilot-pro/pull/188, make keystroke properties optional and fall back to defaults (except for `code`).
> Make keystroke props optional and fall back to default values

- app/static/css/toggle.css
- app/templates/styleguide.html
Add toggle button to style guide, as needed in https://github.com/tiny-pilot/tinypilot-pro/pull/197.
By the way: I just realised that I always introduce general style-related things in the community repo, even if we only use them in pro. Intuitively, that makes sense to me, because having diverging styling rules might be very confusing. On the other hand, it can also be confusing to see things that don’t appear to be used anywhere… 🤔 Anyway, I’d suggest to continue following that habit for now, because otherwise it’d be even more confusing. A potential topic for discussion, though.
> Add toggle button to style guide

- app/static/js/settings.js
Fixes https://github.com/tiny-pilot/tinypilot/issues/727.
For persisted settings, we can’t determine whether the user had explicitly set the cursor or whether it was just the former default, because we always persist the [full settings including defaults](https://github.com/tiny-pilot/tinypilot/blob/792e2b783eaea3741bdb46fcacc620218192a49b/app/static/js/settings.js#L12). I’d think that’s not a big deal, though.
> Change default cursor from `crosshair` to `default`

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/custom-elements/video-settings-dialog.html
- app/templates/index.html
Fixes part 2 of https://github.com/tiny-pilot/ansible-role-tinypilot/issues/144.
`<script src="">` fetches are dumped into the global scope, and in contrast to CSS the shadow’s JS scope is **not** isolated. We can therefore just pre-fetch all global JS and thereby ensure that it’ll only be requested once.
Note to self: fix in Pro as well after this is merged.
> Import all global JS upfront

- app/static/css/button.css
- app/static/css/style.css
- app/static/css/toggle.css
- app/templates/custom-elements/button-dropdown.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/error-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/styleguide.html
Addresses https://github.com/tiny-pilot/tinypilot/issues/743; I revised the look of all interactive controls, to give them a more “materialistic” (3-dimensional) appearance and tune their sizing a bit. This PR actually goes a bit beyond the scope of that issue, but for me the proposed changes would be atomic in a **visual** sense. (From a practical point of view, we also don’t have *that* many elements anyway.)
- Reduce the default button size; the `.btn-small` variant is practically obsolete now, we can clean it up ~in a subsequent step~ right away.
- All buttons have a slight border to increase their contrast. They also have a subtle background gradient, as if they were “rearing up” a little bit.
- Equivalently to that, the input field and the toggle button have inset shadow, as if they …
> Make styling of interactive elements look more “materialistic”

- app/threads.py
- app/update_logs.py
In order to hide the implementation details of using eventlet (and for consistency) we're porting over the [threads.py](https://github.com/tiny-pilot/tinypilot-pro/blob/master/app/threads.py) module from TinyPilot Pro.
This PR comes off the back of a [review comment here](https://github.com/tiny-pilot/tinypilot/pull/742#pullrequestreview-710988924).
> Port over the threads module from TinyPilot Pro.

- app/static/js/app.js
- app/static/js/controllers.js
- app/static/js/keyboardstate.js
- app/static/js/keycodes.js
- app/static/js/keystrokes.js
Part of https://github.com/tiny-pilot/tinypilot/issues/746, and follow-up of https://github.com/tiny-pilot/tinypilot/pull/757, where I forgot this unfortunately.
[Strict mode is on by default for ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules), so the directives are not needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/758)
> Remove `use strict` directives from ES6 modules

- .gitignore
- CONTRIBUTING.md
- app/main.py
- app/socket_api.py
- dev-scripts/mock-scripts/collect-debug-logs
- dev-scripts/serve-dev
- dev_app_settings.cfg
Dependent on https://github.com/tiny-pilot/ansible-role-tinypilot/pull/148
The only place we use `KEYBOARD_PATH` and `MOUSE_PATH` is in the socket API. Now that these variables are stored in the Flask app config, we need to have a handle on the current Flask app in order to reference these variables. To avoid circular imports, the [Flask docs](https://flask.palletsprojects.com/en/2.0.x/appcontext/#purpose-of-the-context) suggest using `flask.current_app` which is only available when a request comes in. This means that we can't have a global `keyboard_path`/`mouse_path` variable like before. Instead, I opted for [helper functions](https://github.com/tiny-pilot/tinypilot/blob/0999f46dc9fbaf84163fa10c35d8d03e63106a3d/app/socket_api.py#L20-L41) to be called within the context of a request. …
> Load keyboard and mouse paths from Flask config file

- app/static/js/paste.js
Fixes https://github.com/tiny-pilot/tinypilot/issues/730. The problem is MacOS-specific, because 1) on MacOS the Meta (⌘) key is used instead of Ctrl, and 2) Firefox and Chrome differ in their keycode for said Meta key.
I simplified the code a bit, for long monotonous checks like here I find list expressions easier to understand than boolean statements.
I’ve tested on both Chrome and Firefox, so in case you don’t have a Mac at hand for QAing I think it should be fine.
I also checked the rest of the codebase for this issue, but couldn’t find any other place where we might have forgotten about MacOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/756)
> Properly recognize pasting shortcut on MacOS

- app/static/css/style.css
- app/templates/styleguide.html
Small UI issue: I noticed that the monospace class didn’t have any effect on the input field, due to CSS selector specificity. The monospace font is better suited for technical jargon/values, because it’s designed to make individual characters distinguishable. E.g. if you compare:
- |IlliO0o'"' (regular font)
- `|IlliO0o'"` (same copy, but monospace font)
I need this for https://github.com/tiny-pilot/tinypilot-pro/issues/216. But it also fixes the hostname dialog, which should be (have been) monospace too.
It’s quite hard to get the sizing exactly equal on all browsers / OSses. I’ve tested on Mac (Firefox / Chrome / Safari), and Ubuntu (Firefox), and it appeared to be roughly the same everywhere. In the end, the goal is that input field and button always have the same visual height. …
> Fix monospace variant of input field

- README.md
Nobody donates through the donation link, so it's not worth the README real estate. Users can still donate through the Github link at the top of the page (controlled by .github/FUNDING.yml)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/765)
> Remove donation link from README

- quick-install
Fixes #764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/768)
> Explicitly target buster as release version during apt-get update

- app/templates/custom-elements/overlay-panel.html
The overlay panel was set to overflow: scroll, which caused scrollbars to appear on the right and bottom of the page. These aren't necessary, so this change makes it overflow: auto, causing the scrollbars to disappear unless they're actually scrolling content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/763)
> Remove scrollbars on overlay elements

- requirements.txt
We were getting a warning during install that eventlet was incompatible with our version of dnspython
>eventlet 0.31.0 has requirement dnspython<2.0.0,>=1.15.0, but you'll have dnspython 2.1.0 which is incompatible.
Downgrading to 1.16.0 fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/774)
> Downgrade dnspython to 1.16.0

- app/static/css/button.css
- app/static/css/style.css
- app/templates/custom-elements/overlay-panel.html
- app/templates/styleguide.html
We only have styling for the disabled state of the success button, but not for the others. For the WOL overlay I need a disabled action button, and while I was on it I also did the error one.
- I had to change the `--brand-red-light` to `--brand-red-background`, since we are running out of labels… It’s only usage is as background colour of the error overlay.
- I also adjusted the colour values a bit for slightly better contrast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/773)
> Add disabled state for all button variants

- app/js_to_hid.py
- app/js_to_hid_test.py
This code block used to be able to throw a KeyError, but as of #511, _map_keycode handles the KeyError internally, so there's no opportunity for it to bubble up to the convert() function, making the try/catch unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/777)
> Remove extraneous try/catch from js_to_hid

- app/static/js/controllers.js
- app/static/js/csrf.js
- app/templates/custom-elements/update-dialog.html
This PR wraps all unsafe HTTP requests (made from the frontend) with a function that retries the request once more if it fails due to a stale CSRF token.
1. Frontend gets loaded in the browser
2. Backend restarts for whatever reason. This changes the CSRF token.
3. Frontend makes a unsafe HTTP request (i.e. PUT, POST, DELETE) to the backend.
4. The request fails with a 403 Forbidden HTTP error because the frontend has an outdated CSRF token.
5. The frontend refreshes its CSRF token
6. The original request (in step 3) is retried once.
Seeing as the retry behaviour is applied to the individual controller functions, a race-condition is created when calling these controllers in "parallel" and passing them to `Promise.all`. Currently this race-condition can only happen in the [`video-dialog` …
> Add automatic request retry on CSRF failures.

- app/static/js/app.js
When the user clicks the Ctrl-Alt-Del shortcut from the Actions menu, the key history shows only a Delete keystroke, which might make users wonder whether we sent the keystroke correctly.
This change adds the Control and Alt keystrokes to match a real user's keystrokes and to generate a clear keystroke history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/790)
> Clarify keystroke history on Ctrl-Alt-Del

- app/templates/custom-elements/remote-screen.html
Applies uStreamer's dual_final_frames=1 option to work around a bug in how Chrome and other browsers handle MJPEG when uStreamer's --drop-same-frames option is in use.
uStreamer's documentation suggests that this is a Safari/Webkit-specific workaround, but I've verified that this affects Chrome, Firefox, and Edge as well.
Fix confirmed on:
* Chrome 93 x64 (Windows)
* Edge 94 x64 (Windows)
* Firefox 92 x64 (Windows)
---
To reproduce this, I reduced FPS to 5, so uStreamer was running with the following settings on a TinyPilot Voyager:
```bash
ustreamer \
--port 8001 \
--encoder omx \
--format uyvy \
--desired-fps 5 \
--workers 3 \
--drop-same-frames 30 \
--persistent \
--dv-timings
```
I loaded the page in Chrome 93 x64 (Windows) and moved the mouse both before and after the fix. …
> Apply a uStreamer workaround for browser bugs in MJPEG handling

- quick-install
TinyPilot bootstraps an Ansible environment in order to install TinyPilot in quick-install. We've been stuck on an old version of the cryptography package for a while because it required a Rust environment to install for a while, but now binary builds are available in wheel, so we don't need Rust to build it anymore, and we may as well be on the latest version.
This also lets us get rid of the workaround where we had to explicitly install the wheel package first. Now we can upgrade to a recent version of pip and it will use binary wheels where available instead of building packages locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/810)
> Upgrade to cryptography==35.0.0 in ansible environment

- app/socket_api.py
I added debug logging when investigating #818, and I feel like it's useful to have permanently. It only logs when the log level is set to DEBUG, so this won't affect typical usage, but it will be helpful if we need to diagnose issues with keystroke forwarding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/819)
> Add debug logging for raw keystroke messages

- app/static/css/style.css
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/inline-message.html
- app/templates/styleguide.html
Applied `inline-message` changes from pro, effectively backporting `inline-message` and `change-hostname-dialog` components.
Resolves #806.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/820)
> Backport `inline-message` from pro

- app/hid/mouse.py
- app/static/js/mouse.js
JS and HID have opposite semantics for representing vertical scrolling. JavaScript represents downward scrolling with a positive number, whereas HID indicates it with a negative number.
We were previously flipping the sign in JS, but that's a poor place for it because the server is responsible for translating between JS events and HID messages, so this change moves the translation to the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/823)
> Move negation of mouse scroll wheel to the server

- app/main.py
This fixes a bug where TinyPilot's log formatter at some point in our history got disconnected from the root logger, so we were creating a log formatter and discarding it without applying it to the actual logger.
This applies our log format to the root logger and adds in milliseconds-level precision because the default Flask logger includes it, and it might be useful for debugging at some point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/828)
> Set explicit format for log messages

- app/main.py
- dev-scripts/build-python
- scripts/update-service
We need to import log.root_logger before loading any other modules, but that causes isort to complain about the import order. Adding the --top flag tells isort that we intentionally want this import to be first.
This allows us to import log.root_logger first without disabling isort.
pylint will still complain, but we can rebase onto #833 once that's merged in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/834)
> Use isort --top flag to force files to import log.root_logger first

- .pylintrc
Add a few more pylint rule suppression for import issues that we're already using isort to check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/836)
> Disable pylint checks for import rules that isort checks already

- .github/workflows/merge-pro.yml
On a new commit to master branch in community repo, a merge PR is created in the pro repo, assigned to the author of the triggering commit.
When the committer has no access to the pro repo, the PR is still created but with no assignee.
Resolves #838.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/839)
> Automatically merge from Community -> Pro

- .pylintrc
pylint flags on lines that are longer than the column limit because its default rule is to only allow URLs within comments or if they're the only value on the line.
Our style guide allows long URLs on lines for more scenarios:
See https://google.github.io/styleguide/pyguide.html#32-line-length
This change adjusts pylint to better match our style guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/841)
> Adjust pylint rules to allow URLs longer than the column limit

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/inline-message.html
The style guide says of inline-message:
>The text should be left-aligned, even in an otherwise centered context.
So we should do this in the template rather than relying on the client to set the style in every instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/854)
> Default inline-message to text-align left

- dev-scripts/build-python
We don’t provide [the custom (sensitive) logger](https://github.com/tiny-pilot/tinypilot/pull/830) for our tests, hence a call to `logger.info_sensitive` during the tests makes the test crash. This problem didn’t surface so far, because none of the modules that use sensitive logging have tests yet.
The easiest way I can think of would be to globally load the module in the test runner, which I think is also the closest imitation of the behaviour when the app is run via `main.py`. (I.e. it’s safe to rely that the logger is just there.)
A downside is that you need to remember doing this when running tests selectively while developing. For example, I run individual test files in the PyCharm IDE directly; for that I can put an `import log` at the top of the file temporarily, which works well …
> Provide custom (sensitive) logger in all tests

- dev-scripts/build-python
Fixes https://github.com/tiny-pilot/tinypilot/issues/861, which was caused by https://github.com/tiny-pilot/tinypilot/pull/859.
`--module`/`-m` can’t be specified multiple times, but instead you just give it a list of modules to load.
[The tests are all executed again](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/1839/workflows/1d3b7e9b-0f72-4201-b3b8-b1010068e7a4/jobs/6575), I have also verified this locally by changing a random assertion to see it fail.
The test coverage is slightly increased now, from 55% to 56%, because the imported `log.py` file is now always counted, even if it’s not executed by any of the underlying test code.
Thanks again @rw4nn for spotting this!
--- …
> Fix test run configuration

- app/templates/custom-elements/feature-pro-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/styleguide.html
While testing https://github.com/tiny-pilot/tinypilot-pro/pull/343, I noticed that we forgot to use title case here. I’ve also document that rule in the style guide, for future reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/866)
> Use title case in headlines

- app/templates/custom-elements/remote-screen.html
Marked as Draft to come up with a good solution that works for everyone.
I had to implement JS to make this work , not sure if it can be done with CSS alone.
I believe I had originally suggested having multiple view options depending on user preference but we ended up only using default screen and full screen.
The min-width 992px is something I added to correct small screen when keyboard is visible.  I can remove this if not needed but it's there so I don't forget.
Resolves #797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/878)
> Scale remote screen size to fit browser height

- app/socket_api.py
These names date back to the original addition of websockets to the app (b45c7ccf3437aafc10b19d6e5874911e5ccc00f1). I used the names test_connect and test_disconnect based on the Flask-SocketIO documentation, thinking that the test_ prefix was a convention. I now realize it was just for demonstration purposes, and the test_ prefix is meaningless.
https://flask-socketio.readthedocs.io/en/latest/getting_started.html#connection-events
This changes the names to on_connect and on_disconnect so the functions are not confused for test functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/879)
> Give clearer names to the Python websocket connection handlers

- app/templates/custom-elements/shutdown-dialog.html
Fixes https://github.com/tiny-pilot/tinypilot/issues/882.
I’ve also quickly revisited all the other dialogs again, just to be safe, but they seem all fine.
https://user-images.githubusercontent.com/83721279/149218572-3030e9e2-7ea1-4ef8-ae37-dd6e4be58583.mov
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/887)
> Prevent closing dialog after shutdown complete

- app/request_parsers/hostname.py
- app/request_parsers/json.py
- app/request_parsers/json_test.py
- app/request_parsers/message.py
- app/request_parsers/video_settings.py
Part of #876. (implementation in community repo)
Return parsed variables directly from JSON message parser, as a tuple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/890)
> Return parsed variables directly from JSON message parser

- app/static/css/style.css
- app/templates/custom-elements/menu-bar.html
Part of https://github.com/tiny-pilot/tinypilot/issues/785#issuecomment-1025139976.
One note about the new color: the “plutonium green” that we use in the logo is different from the green that we have in the [app design’s color palette](https://github.com/tiny-pilot/tinypilot/blob/183eaf2e1a48af96fe48a26245b640b7c54e8fd3/app/static/css/style.css#L35). I think we should only use the logo’s green scarcely, to keep it distinct and unique (“shiny”). For something like this badge it seems to be a good fit, though, because the badge is somewhat marketing- or brand-related.
Since the logo green is a specific color that’s defined externally, I think it’s okay to hard-code the RGB value instead of using our usual way of defining the colors.
---
This change is [<img …
> Introduce “Pro” badge for menu items

- README.md
This PR explains how to run the [H264 docker image](https://hub.docker.com/r/jdeanwallace/janus-ustreamer) on either a Hobbyist or Voyager device.
This PR depends on https://github.com/tiny-pilot/ansible-role-tinypilot/pull/183 being merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/914)
> Update instructions on how to run Janus & uStreamer on a Hobbyist or Voyager device

- app/socket_api.py
For debugging purpose, I think it’s useful for the socket connection handlers to also log the socket ID, so that the corresponding “connect” and “disconnect” events can be matched more easily.
The socket ID is internal, and I wouldn’t classify it as personal information which we would have to flag as sensitive.
Note that we have also https://github.com/tiny-pilot/tinypilot-pro/issues/387, which this is somewhat related to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/916)
> Log out client id for socket connection events

- app/atomic_file.py
- app/atomic_file_test.py
This change is needed for the fix for https://github.com/tiny-pilot/tinypilot/issues/917.
It’s the `atomic_file` package plus the tests taken over verbatim from the Pro repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/919)
> Backport `atomic_file` package from Pro

- app/atomic_file.py
- app/atomic_file_test.py
This change is needed for the fix for https://github.com/tiny-pilot/tinypilot/issues/917; depends on https://github.com/tiny-pilot/tinypilot/pull/919.
It extends `atomic_file.create` with an additional, optional parameter for specifying the chmod mode on the new file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/920)
> Extend `atomic_file` to set file permissions

- app/secret_key.py
- app/secret_key_test.py
Hey @jdeanwallace, sorry for overloading you with PRs this week…
This is a follow-up of https://github.com/tiny-pilot/tinypilot/pull/921. Per discussion in https://github.com/tiny-pilot/tinypilot/issues/917, we wanted to recreate corrupt secret key files on the fly, rather than letting the server fail altogether.
Some notes:
- This mechanism obviously wouldn’t work for cases such as where we don’t have any permissions on the file at all (however that could happen). But for the regular “user has accidentally altered the file contents” case, it should suffice. Also, if the content is valid but only the permissions are wrong, we could handle it more fine-granularly. I don’t think that’s worthwhile, though.
- I debated whether to change the name of `get_or_create`, because of the new …
> Recreate corrupt Flask secret key, instead of failing

- README.md
This PR is part of https://github.com/tiny-pilot/ansible-role-tinypilot/issues/179.
This PR depends on https://github.com/tiny-pilot/ansible-role-tinypilot/pull/184 being merged.
This PR updates the instructions on how to run the [H264 docker image](https://hub.docker.com/r/jdeanwallace/janus-ustreamer). We no longer need to differentiate between the Hobbyist and Voyager devices because the we no longer run uStreamer in the docker image. We can just let the `quick-install` script set the appropriate uStreamer settings. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/922)
> Update run instructions for H264 docker image

- README.md
This PR updates the instructions on how to run the Janus Docker container on both a TinyPilot Voyager & TinyPilot Hobbyist device.
On a Voyager device, we need to specify that we're using a capture chip<s> and change the uStreamer format to JPEG</s>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/938)
> Update Janus Docker container instructions

- app/templates/custom-elements/remote-screen.html
- app/templates/index.html
Part of https://github.com/tiny-pilot/tinypilot/issues/877.
In order for us to swap out the MJPEG `<img>` element with an H264 `<video>` one, we need to parametrize the `<remote-screen>` component.
One relatively clean implementation is to slot in the screen content from the outside into the `<remote-screen>` component. There is a working POC of this in https://github.com/tiny-pilot/tinypilot/pull/940.
This PR is a non-functional refactoring, so the behaviour and appearance should be the same as before. This not just for the (re-)sizing behaviour, but also for how the mouse coordinates compute.
For simplicity, I’ve renamed the internal element’s `id` to just `#screen`, because it should be clear what it is from the context. Something like `#content` or `#canvas` would sound too generic to …
> Make `<remote-screen>` content injectable

- app/static/js/webrtc-video.js
As @jotaen4tinypilot [discovered](https://github.com/tiny-pilot/tinypilot/issues/948#issuecomment-1087923465), the uStreamer Janus plugin takes a few seconds to initiate the H.264 stream internally. This results in the [watch command](https://github.com/tiny-pilot/tinypilot/blob/06882c61440258a9ce2067e7d6bc261d507f298d/app/static/js/webrtc-video.js#L71) returning a 503 error. This PR retries the watch command when a 503 error is received.
The fix is ported over from our "Guide to H.264 streaming" [sample code](https://github.com/tiny-pilot/ustreamer/blob/a8dfa96db0c1ed5ae216a58f4f07a955cd23a212/docs/h264.md#sample-code).
Resolves https://github.com/tiny-pilot/tinypilot/issues/948
--- …
> Fix WebRTC cold start behaviour

- app/templates/custom-elements/remote-screen.html
Part of https://github.com/tiny-pilot/tinypilot/issues/946
This PR adds a `fullscreenMaximize` attribute to the `remote-screen` element to either maximize the width or height of the screen element instead of using JS to add/remove CSS classes.
This change is needed in order to refactor the video & img elements back into the `remote-screen` component (based on this comment https://github.com/tiny-pilot/tinypilot/pull/950#pullrequestreview-935264560) because adding/removing CSS classes from multiple screen elements would be tedious.
This PR does **not** address the known "[misaligned mouse coordinates](https://github.com/tiny-pilot/tinypilot/issues/964)" bug. That bug is still present in this PR.
---
@jotaen4tinypilot This PR is similar to [one of the commits you've already …
> Use html attributes to maximize the screen size in fullscreen mode

- app/templates/custom-elements/menu-bar.html
We were assigning almost every `<a>` tag in the menu bar a unique ID so that we could use JavaScript to map those IDs to an event to emit when the `<a>` tag is clicked.
I realized we could simplify things by skipping the IDs and just defining the associated event in the `<a>` tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/971)
> Refactor event handling in menu bar

- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/styleguide.html
I just noticed that Chrome puts a red squiggle under 'tinypilot' because it flags it as an unrecognized word. We can add HTML attributes to prevent this behavior, and while we're at it, we may as well prevent autocomplete and friends on mobile devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/972)
> Remove spellcheck and other formatters on hostname input

- dev-scripts/check-bash
Part of https://github.com/tiny-pilot/ansible-role-tinypilot-pro/issues/84: use “standardized” `check-bash` script, [as introduced here](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/198).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/974)
> Use standardized `check-bash` script

- app/templates/custom-elements/about-dialog.html
- app/templates/custom-elements/credit-entry.html
Previously, we broke our typical pattern for custom elements by placing the template for entries in the list of credits was in a template within the same file as the about page dialog rather than in its own file, as we normally do.
Combining the element had an unintended I overlooked: it duplicates the same `<style>` tag and rules ~40 times in the HTML.
I imagine there's a way to do this correctly without putting the template into a separate file, but I don't think it's worth the dev resources to dig into it at the moment.
This change ungroups the custom elements so that the template for entries in the credits has its own distinct file and follows our normal patterns for custom elements.
--- …
> Put template for About dialog credits in a separate file

- .circleci/config.yml
- bundler/.gitignore
- bundler/bundle/ansible.cfg
- bundler/bundle/install
- bundler/bundle/install.yml
- bundler/bundle/lib.sh
- bundler/bundle/requirements.txt
- bundler/create-bundle
- bundler/get-tinypilot.sh
This merges the https://github.com/tiny-pilot/tinypilot-bundler repo into this repo, per discussion in https://github.com/tiny-pilot/tinypilot-bundler/issues/19.
Changes:
* Changed paths to reflect the placement within the new repo.
* Deleted the README
* Deleted the `dev-scripts` folder as the same scripts already existed in this repo.
* Deleted the `check_bash` and `check_whitespace` CircleCI jobs as they already existed in this repo.
After we merge this in, the tinypilot-bundler repo will become obsolete and we'll mark it as read-only.
Fixes https://github.com/tiny-pilot/tinypilot-bundler/issues/19
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/986)
> Add logic for building TinyPilot install bundles

- .circleci/config.yml
Our convention is to default to the CircleCI base image when we don't need anything specific in the Docker image, so this changes the build_bundle CI step to use cimg/base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/991)
> Use the CircleCI base convenience image for build_bundle

- .circleci/config.yml
Add a CircleCI job to upload completed builds to our storage bucket on Backblaze.
Currently, our bundles are always named `tinypilot.tar`, so we'll keep overwriting the same file. The upload logic uses wildcard matching so that once we [change the bundle names](https://github.com/tiny-pilot/tinypilot-bundler/issues/9), this will start uploading bundles to distinct locations and shouldn't need to be updated.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/990)
> Upload completed bundle to Backblaze

- bundler/.gitignore
I think we missed to add the Debian package file to `.gitignore`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/999)
> Exclude `.deb` files in bundler directory from git

- bundler/create-bundle
Adds metadata to the bundle filename so that the bundles have names like `tinypilot-2022-06-17T1706Z-6f23b05.tar` instead of just `tinypilot.tar`.
Ultimately, I think we should put this logic into the script for [generating the Debian package](https://github.com/tiny-pilot/tinypilot-bundler/issues/60), but in the meantime, this lets us upload distinct files to Backblaze (#990).
Fixes https://github.com/tiny-pilot/tinypilot-bundler/issues/9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/992)
> Add richer information into the bundle filename

- .circleci/config.yml
Resolves https://github.com/tiny-pilot/tinypilot/issues/1000
This PR adds a CircleCI filter to only build and upload bundles in the `master` branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1014)
> Limit CI bundle builds/uploads to the master branch.

- .pylintrc
- app/atomic_file_test.py
- app/update/launcher.py
- app/update/result_store_test.py
- app/update/settings_test.py
Thank you @mtlynch for suggestions on #1013
pylint now has a suggestion for using the with keyword in places where the code allocates resources. This change bypasses the check for current test cases that perform a manual tear down or for child processes not managed by parent.
Fixes https://github.com/tiny-pilot/tinypilot/issues/997
I'm a newcomer to oss so thank you for the tag:good first issue !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1020)
> Remove global suppression for 'consider-using-with' pylint rule

- .circleci/config.yml
- bundler/create-bundle
- bundler/get-tinypilot.sh
It's not a huge space savings right now, but it costs basically nothing to compress, and it might have a more meaningful impact in the future if our bundle size increases. It's much easier to change formats now before anything is using the bundles, so we're changing to .tgz.
| Bundle | Size |
|------------|----------|
| [tinypilot-community-20220622T1634Z-725b1a1.tar](https://bundles.tinypilotkvm.com/community/tinypilot-community-20220622T1634Z-725b1a1.tar) | 800 KB |
| [tinypilot-community-20220624T1527Z-56e4671.tgz](https://bundles.tinypilotkvm.com/community/tinypilot-community-20220624T1527Z-56e4671.tgz) | 629 KB |
Related: https://github.com/tiny-pilot/gatekeeper/pull/37
Fixes #1002 …
> Compress TinyPilot bundle with gzip

- quick-install
We added a requirement on pip 21.3.1 when the standard pip that shipped with Raspberry Pi OS was older than 21.3.1, and we wanted a newer feature. Now, Raspberry Pi OS ships a newer version of pip and we're forcing the system to our particular version, which is unnecessary.
This change relaxes the requirement on the pip version to be 21.3.1 or later, so we only have to reinstall pip if the system's version is pretty old.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1033)
> Upgrade pip to a minimum version rather than a specific version

- bundler/bundle/requirements.txt
- quick-install
According to this thread, this line was always erroneous and we should just remove it: https://github.com/pypa/pip/issues/4022
It doesn't seem to harm anything on Raspberry Pi OS, but it causes problems on other distros.
Fixes #1031
Fixes #1015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1032)
> Remove pkg-resources from list of quick-install requirements

- get-tinypilot.sh
We have this check in our legacy quick-install script (https://github.com/tiny-pilot/tinypilot/blob/fa2a5fed814e3ae80415b58918d71e28fbcd10c7/quick-install#L95L132) but we haven't ported it over to our new flow.
We still need this to make sure that Pro users don't accidentally downgrade to Community when trying to update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1039)
> Prevent users from accidentally downgrading from TinyPilot Pro to Community

- app/api.py
- app/version.py
- app/version_test.py
Resolves https://github.com/tiny-pilot/tinypilot/issues/1021
Notes:
1. In local development mode (i.e. debug mode) we return [a dummy version hash `0000000`](https://github.com/tiny-pilot/tinypilot/blob/bb8c7f7999544961dba5e6e58149e940058393cb/app/version.py#L38).
2. In order to detect if we're in dev mode, we access `flask.current_app.debug`. This makes it notoriously difficult to write tests because we need to initialize a new Flask `app` to be able to give the unit test an application context. Anyway, instead of doing that I just pulled the `flask.current_app.debug` into its own function (i.e. [`_is_debug`](https://github.com/tiny-pilot/tinypilot/blob/bb8c7f7999544961dba5e6e58149e940058393cb/app/version.py#L21-L22)) and [mocked that …
> Read local version from `VERSION` file.

- .circleci/config.yml
- bundler/create-bundle
create-bundle needs to translate Git URLs to folder names after cloning. Previously, we were doing it hackily with string replacement, but @jdeanwallace pointed out that we can do it with the basename bash utility, so this switches to basename.
I tried a test build, and it built successfully:
https://bundles.tinypilotkvm.com/community/tinypilot-community-20220630T1652Z-1b17e24.tgz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1042)
> Use bash basename to convert URLs to folder names

- get-tinypilot.sh
This PR was cherry-picked from https://github.com/tiny-pilot/tinypilot/commit/be853eb8eb60a22450f1a90575ed14b0ac9e81f0 to merge into `master` instead of `update-overhaul` ([see discussion here](https://github.com/tiny-pilot/tinypilot/pull/1048#issuecomment-1177622659)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1049)
> Specify custom temporary directory for use with `mktemp`

- app/license_notice.py
As part of the update overhaul, TinyPilot no longer has a permanent location for the Ansible install virtual environment, so we're switching the license links to point to Internet URLs for the licenses rather than internal paths on the device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1054)
> Update paths to licenses for Ansible dependencies

- README.md
Reverts tiny-pilot/tinypilot#1045
Replaced by https://github.com/tiny-pilot/tinypilot/pull/1058
We're going to move the use of `sudo` to within the `get-tinypilot.sh` script ([see discussion here](https://github.com/tiny-pilot/tinypilot/pull/1053#pullrequestreview-1037631949)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1057)
> Revert "Add `sudo` to install instructions."

- get-tinypilot.sh
Reimplements https://github.com/tiny-pilot/tinypilot/pull/1045
Instead of calling `get-tinypilot.sh` with `sudo`, we rather use sudo within `get-tinypilot.sh`. This way we preserve environment variables like `$FORCE_DOWNGRADE` that can be read by `get-tinypilot.sh`.
Notes:
1. <s>We also need to use `sudo` when cleaning up the temp directory because it contains files owned by the root user. For example:
```bash
...
Operation cancelled by user
+ clean_up
+ rm -rf /var/tmp/tmp.QilazmMevp.tgz /var/tmp/tmp.Vqsl9SLjqM
rm: cannot remove '/var/tmp/tmp.Vqsl9SLjqM/venv/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl': Permission denied
rm: cannot remove '/var/tmp/tmp.Vqsl9SLjqM/venv/share/python-wheels/distro-1.3.0-py2.py3-none-a …
```
> Use `sudo` when installing bundle.

- .circleci/config.yml
- Dockerfile
Resolves https://github.com/tiny-pilot/tinypilot/issues/1055
Dependent on https://github.com/tiny-pilot/tinypilot/pull/1061
This PR alters the Debian package `preinst` script to only remove `/opt/tinypilot` (& `/opt/tinypilot-updater`) when upgrading from the git-based update flow.
Notes:
1. I've enable [here-documents](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#here-documents) in our Dockerfile, like we have done in the [`janus-debian` Dockerfile](https://github.com/tiny-pilot/janus-debian/blob/2a8f0627476adc6bad1149a5a7e53a4f3aa07795/Dockerfile#L1-L3). This allows for cleaner looking multiline `RUN` commands.
--- …
> Handle `preinst` cleanly in Debian package.

- .circleci/config.yml
- Dockerfile
Resolves https://github.com/tiny-pilot/tinypilot/issues/1056
This PR adds a `prerm` script to our Debian package that removes `__pycache__` directories and `.pyc` files when the Debian package is removed via `apt-get remove tinypilot`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1062)
> Add Debian package `prerm` script.

- .dockerignore
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/495
The PR removes the `get-tinypilot.sh` script from the TinyPilot Debian package. [See full explanation here](https://github.com/tiny-pilot/tinypilot-pro/issues/495#issuecomment-1191416047).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1064)
> Add `get-tinypilot.sh` to `.dockerignore` file.

- Dockerfile
- bundler/bundle/install
- get-tinypilot.sh
Resolves https://github.com/tiny-pilot/ansible-role-tinypilot/issues/206.
As discussed in the ticket, we bring back the permanent `/opt/tinypilot-updater` folder, to stay backwards compatible with code that still relies on that path. I also had to “revert” the recent [`venv`-related changes](https://github.com/tiny-pilot/tinypilot/pull/1059), because in order for the privileged scripts to run the ansible roles, [they expect the `venv` folder to exist](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/14cc40e7e53260628be09597799533e080bfc7f9/files/update-video-settings#L57-L60).
With the changes from this branch, I was able to produce a TinyPilot installation on a fresh device with functioning video settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Bring back permanent `/opt/tinypilot-updater` folder

- .circleci/config.yml
- bundler/verify-bundle
Resolves https://github.com/tiny-pilot/tinypilot/issues/1006
This PR adds a `check_bundle_integrity` step to our CircleCI workflow. The checks include:
- Bundle size is `>0mb` but `<=5mb`
- Bundle contains `install` script
- Bundle contains Debian package
- Bundle contains Ansible roles
I've tested the new CircleCI workflow here:
https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2374/workflows/68256900-3f8e-486f-a33a-a0f84a18a55d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1066)
> Add smoke test for bundle integrity.

- .circleci/config.yml
Resolves https://github.com/tiny-pilot/tinypilot/issues/1067
This PR makes sure that our CircleCI `e2e` step will use the correct bundle build file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1068)
> Run e2e testing after bundle upload.

- .circleci/config.yml
In order to test https://github.com/tiny-pilot/tinypilot/pull/1046 (https://github.com/tiny-pilot/tinypilot/issues/1027), we temporarily change the CircleCI config to build from the `update-overhaul` branch. That way, the release bundles are always built from the `update-overhaul` branch during the testing/QA phase. We also avoid that merging unrelated changes into `master` would cut a new release and overwrite a testing release.
Before eventually merging https://github.com/tiny-pilot/tinypilot/pull/1046, we resolve the `TODO` comment and switch the filters back to `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1072)
> Temporarily cut all releases from `update-overhaul`

- .circleci/config.yml
- bundler/create-bundle
Related to https://github.com/tiny-pilot/tinypilot/issues/1071
This PR adds the ability to specify a specific branch/version per ansible role dependency.
A successful CircleCI build:
https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2401/workflows/847cf2c0-50e4-47a1-b753-d3fde5ee8f4a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tiny-pilot/tinypilot/1075)
> Bundle a variable version of ansible role.

- app/templates/custom-elements/remote-screen.html
I spoke to a customer who pointed out that this is wasted space, especially when the window size is reduced, and we could just use the full width of the window.
I originally kept the margins just because it looked a little tidier not to have it extend completely into the edges, but testing the full bleed behavior does look about the same aesthetically, and it seems like an improvement pragmatically.
---
https://user-images.githubusercontent.com/7783288/187705066-b63e452c-06d0-44e5-9de8-c5e17bb08f95.mp4
---
https://user-images.githubusercontent.com/7783288/187705089-3e8971cc-2e4f-4a66-8a73-e5e7c664263d.mp4
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1092"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use full window width to display remote screen

- app/find_files/find.py
- app/static/legal/privacy-policy.txt
- app/templates/custom-elements/about-dialog.html
Add a privacy policy to cover the types of data we collect from TinyPilot and link to it from the About page.
We don't collect OS and software version in the Community version yet, but we've included language for it in the privacy policy in case we decide to collect that in the future.
TinyPilot Pro will have adjustments to this policy, as it collects additional information for license checking.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1096"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add a Privacy Policy to About page

- .circleci/config.yml
circleci/* containers are now deprecated, so we should move to cimg/* containers:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1098"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Migrate off of CircleCI's deprecated node.js container

- .pylintrc
For a project of our scale, we don't need the linter to point out when a file is too long. We can consciously decide to let a line grow long for other reasons.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1100"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Disable pylint's too-many-lines rule

- CONTRIBUTING.md
Our coding conventions only covered the underscore prefix for class functions, not for fields. Per discussion in https://github.com/tiny-pilot/tinypilot-pro/pull/583#pullrequestreview-1110732410, we also want to apply this convention for fields, though.
I’ve updated the instructions, and also clarified them a bit otherwise.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1101"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Clarify coding conventions on underscore prefix

- .vscode/extensions.json
Updating VS Code's extensions to match what's in the actual project. vetur is a Vue plugin, so we don't need that. eslint might be useful, but we aren't integrated with it yet in any of the other project config, so we should exclude it until we decide to use it. python, we're currently using in settings.json, but we forgot to include it as a recommended extension.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1104"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix recommended VS code extensions

- app/update/settings_test.py
While working on https://github.com/tiny-pilot/tinypilot/pull/1102, I noticed that there is one test scenario that we didn’t cover yet, so I’ve added it here. (Note, this PR goes into the other one.)
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1103"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add test case for update settings

- app/update/settings.py
- app/update/settings_test.py
Part of https://github.com/tiny-pilot/tinypilot-pro/issues/496. **Only to be merged after https://github.com/tiny-pilot/tinypilot-pro/pull/589 is in, to not break the Pro repo.**
We don’t need the `tinypilot_repo_branch` setting any longer, and we also [don’t need to support it for backwards compatibility](https://github.com/tiny-pilot/tinypilot-pro/pull/564#issuecomment-1232120564), so it can go away.
I made the test titles more generic, to indicate that they are not really about testing individual properties (such as `tinypilot_repo_branch`), but rather about the general functionality.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1102"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove support for obsolete update setting `tinypilot_repo_branch`

- app/templates/custom-elements/video-settings-dialog.html
Part of https://github.com/tiny-pilot/tinypilot/issues/1112.
I did a minor refactoring of the CSS/HTML in the video settings dialog (with almost no visual effect), which I believe will help me make it easier to implement all the upcoming changes.
- Rename CSS classes
- Use `flex` instead of `inline-flex`, for simplicity
- Use `<div>` instead of `<span>` for the value, so we can drop `display: block`.
- Assign CSS class to value’s `<div>`, to avoid having to enumerate (repeat) the individual ids
- For the width and spacing of the `.setting`, use `em` instead of `px`, so that the sizes are relative to the element’s font size. So, e.g., if we increased the font size, the width of the label element would grow automatically.
- Slightly increase the spacing between both settings, and re-align …
> Video Settings dialog: CSS/HTML refactoring

- app/templates/custom-elements/video-settings-dialog.html
Part of https://github.com/tiny-pilot/tinypilot/issues/1112, and based on https://github.com/tiny-pilot/tinypilot/pull/1118.
- Instead of `fps`, we could also write `f/s`, but I think [the former is more widely recognized](https://en.wikipedia.org/wiki/Frame_rate).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1119"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Video Settings dialog: re-word labels, and display units

- app/static/js/app.js
- app/templates/custom-elements/video-settings-dialog.html
Part of https://github.com/tiny-pilot/tinypilot/issues/1112.
This is a non-functional refactoring of the component’s JS implementation, which should help to extend the class with the upcoming functionality.
These are my thoughts behind the changes. Please don’t be scared by the amount of text, it’s (hopefully) all not as complicated as it might seem at first glance 🙈 … I thought it makes more sense to do this all in one collective PR, because many of the changes are related, and we also only need one round of QA’ing.
- I renamed `getSettings` to `initialize`. We are [not consistent with naming these entrypoint methods](https://github.com/tiny-pilot/tinypilot/blob/6073998459e21317800139df38166cd34396d4fd/app/static/js/app.js#L322-L353), but at least `initialize()` appears twice. I think it …
> Video Settings dialog: clean up / simplify component implementation

- app/static/js/app.js
- app/templates/custom-elements/video-settings-dialog.html
Part of https://github.com/tiny-pilot/tinypilot/issues/1112, and based on https://github.com/tiny-pilot/tinypilot/pull/1121.
- Track the initial settings in the same way as we store the default settings.
- For every update in the UI, refresh the “Apply” button and conditionally enable or disable it.
https://user-images.githubusercontent.com/83721279/193251496-b0f4981f-7201-4d40-aaf6-6da940726117.mov
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1122"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Video Settings dialog: disable “Apply” button unless there are changes

- README.md
The link is broken.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1117"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove nonexistent smaller form factor HDMI to USB dongle

- requirements.txt
1.1.3 adds compatibility for Python 3.11. We're not using 3.11 yet, but we may in the future, and users on Ubuntu systems are reporting issues trying to install TinyPilot due to the old version of greenlet.
Fixes #1128 
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1132"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Upgrade to greenlet 1.1.3

- app/static/css/cursors.css
- app/templates/custom-elements/menu-bar.html
We added Cell as an option because it was part of an external user contribution in the early days of TinyPilot to add different pointer options, but I don't think it fits anymore. I can't imagine anyone choosing this as their cursor.
There's a slight bug to this fix in that if the user has already chosen Cell as their cursor, the menu bar will show no cursor selected and the cursor will revert to the browser default. I don't think it's worth the effort to fix this bug since the issue will go away once the user selects a new cursor and nothing negative happens except that the remote screen falls back to the default cursor.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1138"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" …
> Remove Cell as a pointer option

- .pylintrc
- app/api.py
- app/hid/write.py
- app/js_to_hid.py
- app/license_notice.py
- app/request_parsers/json.py
- app/request_parsers/keystroke.py
- app/request_parsers/keystroke_test.py
- app/request_parsers/mouse_event.py
- app/version.py
- app/views.py
- scripts/update-service
Fixes #995
tinypilot currently uses old c-style formatting. In order to avoid any complaints from pylint, the `consider-using-f-string` check was disabled. This PR attempts to fix that by updating potentially problematic lines to use f-strings and then removing this check from the list of disabled rules.
* Change c-style formatting by f-strings.
* Remove `consider-using-f-string` from the disabled rules in `.pylintrc`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1143"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use f-strings in places pylint recommends

- .circleci/config.yml
We're actually building a Debian package, but the name made it sound like the Debian package already exists and we're building a Docker image.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1147"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Clarify name of Debian package build step

- .circleci/config.yml
- .dockerignore
- Dockerfile
- debian-pkg/DEBIAN/postinst
- debian-pkg/DEBIAN/preinst
- debian-pkg/DEBIAN/prerm
- debian-pkg/Dockerfile
This change adjusts how we package files in the Debian package so that we include less by default.
When we originally discussed whether to err on the side of including too much or too little, we didn't consider that including everything makes it more difficult to express where to place files in the Debian package.
This change adds a debian-pkg folder to the root of the repo, and everything within that folder gets placed into the Debian package root. Right now, this allows us to extract the special Debian preinst, postinst, prerm scripts to actual files, which allows shellcheck to flag issues that it can't flag when they're embedded in a Dockerfile.
The other benefit is that it allows us to embed other files that we want to place on the device within this repo. I've created a rough …
> Refactor how we place files in Debian package

- .circleci/config.yml
- .dockerignore
- .gitignore
- dev-scripts/build-debian-pkg
I'm not sure why I thought we needed to use QEMU to build the Debian package, as there are no architecture-specific files in the package. It might have just been that we copy/pasted from Janus without thinking about it too much.
This simplifies the Debian package build to just use standard Docker so that it runs faster and can build on more systems (e.g., those that don't support QEMU). The non-QEMU build runs in about 40s instead of 2m30s.
I tested a full Pro image with this change, and everything works fine: https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot-pro/1900/workflows/96bafbbd-32c8-4910-b918-83a8238dda19
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1149"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on …
> Build Debian package with simple Docker rather than Docker+QEMU

- app/db/store_test.py
Our convention is to use mock.patch.object as opposed to mock.patch because the object version offers better checks (e.g., it will error if we attempt to mock a property that doesn't exist).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1160"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use mock.patch.object in store_test

- debian-pkg/Dockerfile
We have a mismatch between the architecture we declare in the Debian package and the architecture we specify in the filename. The filename was specifying an architecture of armhf, while the Debian package was declaring all.
all is correct, so this change updates the filename to match and makes it harder for the two to go out of sync.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1197"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix Debian package filename to use arch all instead of armhf

- .circleci/config.yml
- dev-scripts/build-debian-pkg
Similar to https://github.com/tiny-pilot/janus-debian/pull/12 we should use --progress=plain to produce less noisy output when running a Docker build on CircleCI.
This change detects whether we're running in CI based on whether the `CI` variables is set (which CircleCI and a few others set) and downgrades the progress output to plain if it is set.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1201"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use docker build --progress=plain on CircleCI

- dev_app_settings.cfg
We no longer need the `USE_WEBRTC_REMOTE_SCREEN` dev env variable because the video streaming mode is now saved in the database.
I didn't catch this when reviewing https://github.com/tiny-pilot/tinypilot/pull/1166
> Remove unused WebRTC dev env variable.

- .circleci/config.yml
This change adjusts filtering in CircleCI so that we build the TinyPilot Debian package and install bundle even in non-main repo branches.
Uploading a bundle changes state on our update server, so we should only do that in our main branch. But all the other steps are fine to run in branches because it doesn't affect state outside of CI. It's often useful to build packages or bundles in the branches if we want to test something end-to-end.
> Build TinyPilot Debian package and install bundle outside the main branch

- .circleci/config.yml
Now that we're building the bundle on non-master branches, it's helpful to store it as a CI artifact in case we want to test the bundle before merging changes into master.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1216"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Store the TinyPilot bundle as a build artifact in CI

- bundler/bundle/install
Part of https://github.com/tiny-pilot/ansible-role-ustreamer/issues/77
As mention in https://github.com/tiny-pilot/ansible-role-ustreamer/pull/78#issue-1466714471:
> To accurately distinguish between Raspberry Pi OS and Debian, we need to use the `ansible_lsb.id` fact because `ansible_distribution=='Debian'` for both OSs. This fact is [only defined if the `lsb-release` apt packages has been installed](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#conditionals-based-on-ansible-facts) prior to ansible gathering facts.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1215"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Ensure `lsb-release` is installed.

- .circleci/config.yml
Use lintian version`2.114.0ubuntu1` instead of `2.114.0ubuntu1.1`.
The lintian version we were using came from the [`jammy-updates` apt repo suite](https://packages.ubuntu.com/jammy-updates/lintian). It suddenly [vanished and broke our build](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2802/workflows/7b1addfb-c4ff-4aff-a7d6-50baa12c292b/jobs/12132?invite=true#step-103-10).
This PR uses the lintian version from the main [`jammy` suite](https://packages.ubuntu.com/jammy-updates/lintian).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1219"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use lintian version from stable apt repo suite.

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
Resolves #1205 by adding a step to the log collection script to check if the overlay / read-only filesystem is enabled.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1218"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Added step to check if overlay filesystem is enabled

- .lintianignore
- debian-pkg/debian/rules
- debian-pkg/debian/tinypilot.tinypilot-updater.service
We previously implemented the tinypilot-updater service in ansible-role-tinypilot, but now that we have a Debian package, it's easier to install the service via the Debian package.
The systemd service definition is verbatim what existed in ansible-role-tinypilot except I've replaced `StandardOutput=syslog` with `StandardOutput=journal` (same with `StandardError`) due to [this lintian warning](https://lintian.debian.org/tags/systemd-service-file-uses-deprecated-syslog-facility).
This change corresponds to the removal of the service from ansible-role-tinypilot: https://github.com/tiny-pilot/ansible-role-tinypilot/pull/241
I tested this manually [on TinyPilot Pro](https://github.com/tiny-pilot/tinypilot-pro/compare/no-updater-scratch?expand=1), and it worked as expected.
<a data-ca-tag …
> Move tinypilot-updater service into core repo

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
Resolves #1220 by capturing the board hardware, revision and model in the debug log.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1227"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add a step to capture the board revision in the debug logs

- bundler/bundle/install
A user reported successful installation on 64-bit Raspbian Bullseye, so we no longer need to block install on aarch64 systems.
Reference: https://github.com/tiny-pilot/tinypilot/issues/929#issuecomment-1358011310
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1238"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove check for 64-bit OS

- README.md
Update the documentation to clarify that we only support 32-bit Raspbian on Buster or later. Previously, it said we support Raspbian Stretch, but that OS is no longer maintained or available, and we haven't tested on Stretch in a long time.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1239"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Specify requirement for 32-bit Raspbian

- bundler/bundle/install
- get-tinypilot.sh
Resolves #1221 by adding a step to check for incompatible hardware to the installation script.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1230"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add incompatible hardware check to installation script

- .circleci/config.yml
- bundler/create-bundle
create-bundle implicitly assumes that the current working directory is the ./bundler directory. This is error-prone, as our other TinyPilot scripts that depend on working directories set the directory themselves.
This change makes create-bundle take responsibility for setting the working directory properly so that callers can execute the script regardless of external working directory.
Our directory traversal is a little odd because we effectively find the script's parent directory, then go up a directory, then go back to the same directory, but I think it's easier to do it that way so that our bash snippet for finding the repo root is the same across scripts.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1247"><img …
> Verify working directory in create-bundle

- scripts/install-bundle
Now that we're storing the TinyPilot bundle as a CI artifact (3c4193bb41748d58ce43cd6535bd52b11d1fccd9), I've found that a convenient way to test changes on a real device is to make a git branch, make changes, push to Github, grab the bundle from CI, and then install the bundle on the device.
This change adds a convenience script to make the process of installing a pre-release bundle easier.
There are a few ugly spots in this change:
The first is that we're shipping a dev-only script as part of normal device install. We can't keep this script in dev-scripts because that's excluded from a TinyPilot install. If we really wanted to keep things tidy, we could keep this in dev-scripts and require the developer to git clone the repo to get this script onto the device, but I think the benefits …
> Add a convenience script for installing TinyPilot bundles

- debian-pkg/Dockerfile
- debian-pkg/debian/tinypilot.postinst
We've been relying on the Ansible role to create the tinypilot user and group, but as we're chipping away Ansible logic, it seemed like a good opportunity to implement this logic in the Debian package instead.
I'm following the guidance here:
https://wiki.debian.org/AccountHandlingInMaintainerScripts
I considered adding the `--disabled-login` flag, but it [doesn't seem to be documented well](https://unix.stackexchange.com/a/96897/152974), and it's not something we had before, so I'm just leaving it out.
Corresponding change in Ansible: https://github.com/tiny-pilot/ansible-role-tinypilot/pull/252
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1240"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Create tinypilot user and group in Debian package

- bundler/bundle/install
Resolves #1243 by modifying the install script to fail if the read-only filesystem is enabled.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1250"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Modify install script to fail if the read-only filesystem is enabled

- app/video_service.py
Part of https://github.com/tiny-pilot/tinypilot/issues/1249
This PR contains an exact copy of https://github.com/tiny-pilot/tinypilot-pro/blob/bc0707716f01fc3c5291ec2c320eb44daa97bb41/app/video_service.py
Thanks to our [uStreamer launcher script](https://github.com/tiny-pilot/ansible-role-ustreamer/pull/89), we now dynamically determine the correct uStreamer command-line options each time the systemd `ustreamer` service is started. That means we no longer need to run an ansible playbook to apply the video settings sitting in `/home/tinypilot/settings.yml`. Instead, we can just restart `ustreamer.service` to redetermine the correct video options.
Seeing as we already have a `video_service` module in TinyPilot Pro that restarts uStreamer & Janus, I thought it would be a good idea to …
> Backport `video_service` module from TinyPilot-Pro.

- app/video_service.py
Part of https://github.com/tiny-pilot/tinypilot/issues/1249
Depends on https://github.com/tiny-pilot/tinypilot/pull/1251
We no longer use the `USE_WEBRTC_REMOTE_SCREEN` environment variable and instead we [save the current streaming mode to our local database](https://github.com/tiny-pilot/tinypilot/blob/24cb3f91cb8bfba3a71d5e407032e0073a768300/app/db/settings.py#L44-L63).
This PR removes the use of `USE_WEBRTC_REMOTE_SCREEN`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1255"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove reference to legacy `USE_WEBRTC_REMOTE_SCREEN` variable.

- debian-pkg/debian/tinypilot.postinst
Without a shell specified, the user defaults to /usr/sbin/nologin, which prevents us from executing commands as the tinypilot user through sudo su.
I tested this on a clean install of Raspbian Buster Lite, and it fixes the `sudo su` issue.
Fixes #1260
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1261"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Specify /bin/bash as the tinypilot user's shell

- app/static/js/webrtc-video.js
- app/templates/custom-elements/remote-screen.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1191
This PR alters our WebRTC client to accept multiple media stream tracks (i.e., video & audio) and adds them to a single media stream played by our `<video>` element.
1. When it comes to switching between MJPEG and WebRTC, I tried to keep the `remote-screen` API more or less the same:
https://github.com/tiny-pilot/tinypilot/blob/465be33957912f5e1fb5e1445d9f148aaf2ce61b/app/templates/custom-elements/remote-screen.html#L321-L325
3. I've altered a [debug log](https://github.com/tiny-pilot/tinypilot/blob/465be33957912f5e1fb5e1445d9f148aaf2ce61b/app/static/js/webrtc-video.js#L174) to give more information about the type of media that has been changed.
Before:
> Remote track changed. mid:"0" added:"false"
> Remote track changed. …
> Accept multiple WebRTC media stream tracks (i.e., video & audio)

- debian-pkg/debian/tinypilot.prerm
Resolves #1264 by checking if `/opt/tinypilot` exists before proceeding with cleanup in `prerm` script.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1272"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Check that /opt/tinypilot exists before cleanup in prerm script

- app/static/js/webrtc-video.js
- app/templates/custom-elements/remote-screen.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1271
When adding/removing a track from the media stream, only display the WebRTC stream when it has at least one video track. 
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1275"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Only display the WebRTC stream when is has a video track.

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
Resolves #1280 by adding a step to the `collect-debug-logs` script that prints out the contents of `/home/tinypilot/settings.yml`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1281"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add step to print settings.yml in debug logs

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
- scripts/is-ssh-enabled
Resolves #1273 by adding a step that checks if SSH is enabled.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1274"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Log whether SSH access is enabled in debug logs

- ansible-role/README.md
- ansible-role/defaults/main.yml
- ansible-role/tasks/install_usb_gadget.yml
- ansible-role/tasks/main.yml
- ansible-role/tasks/ustreamer.yml
- ansible-role/vars/main.yml
Part of https://github.com/tiny-pilot/tinypilot/issues/1174
This PR adds the styles changes, created from running [`dev-scripts/fix-style`](https://github.com/tiny-pilot/tinypilot/blob/e13e4b48fa5705dd94d170a3079bfda1b1d4bd40/dev-scripts/fix-style), needed to fix the [previously failing build](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2956/workflows/18ee9efb-1545-45ce-8446-bb21caaa2213/jobs/13672). This is a non-functional change.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1283"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix style in `ansible-role` directory.

- ansible-role/.circleci/config.yml
- ansible-role/.github/workflows/merge-pro.yml
- ansible-role/.gitignore
- ansible-role/.shellcheckrc
- ansible-role/.yamllint
- ansible-role/LICENSE
- ansible-role/README.md
- ansible-role/defaults/main.yml
- ansible-role/docs/usb-gadget-driver.md
- ansible-role/files/init-usb-gadget
- ansible-role/files/lib/usb-gadget.sh
- ansible-role/files/remove-usb-gadget
- ansible-role/handlers/main.yml
- ansible-role/meta/main.yml
- ansible-role/meta/requirements.yml
- ansible-role/molecule/default/converge.yml
- ansible-role/molecule/default/molecule.yml
- ansible-role/molecule/requirements.txt
- ansible-role/tasks/install_usb_gadget.yml
- ansible-role/tasks/main.yml
- ansible-role/tasks/nginx.yml
- ansible-role/tasks/ustreamer.yml
- ansible-role/templates/tinypilot-app-settings.cfg.j2
- ansible-role/templates/tinypilot.systemd.j2
- ansible-role/templates/usb-gadget.systemd.j2
- ansible-role/tests/check-bash
- ansible-role/tests/check-trailing-newline
- ansible-role/tests/check-trailing-whitespace
- ansible-role/vars/main.yml
Part of https://github.com/tiny-pilot/tinypilot/issues/1174
We have decided consolidate the `ansible-role-tinypilot` repo into the `tinypilot` repo because there's no longer a strong reason to keep the repos separate. Using a single repo would also reduce the git admin that usually comes with developing features that touch both codebases (i.e., pinning repo versions).
This PR simply copies the contents of the [`ansible-role-tinypilot` repo](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/70321141a8f90589962f1ae4069002afad355b7b) into the `ansible-role` directory, with no additional changes. This is a non-functional change.
* I've kept the `ansible-role` directory on the top level of this repo to make the code more visible and accessible. An alternative might have been to store …
> Copy contents of `ansible-role-tinypilot` repo into `ansible-role` directory.

- app/license_notice.py
- bundler/bundle/requirements.txt
Currently, TinyPilot fails to install altogether. The bundle installer cannot resolve the dependency on the `cryptography` pip package version 38.0.3, because there is [no working piwheel yet for that version](https://www.piwheels.org/project/cryptography/), and building from source would require a Rust toolchain to be set up.
[`cryptography` 38.0.2 was yanked](https://cryptography.io/en/39.0.0/changelog/#yanked), so it looks as we currently can only install 38.0.1 via piwheels.
@mtlynch I’ve tested this on the device, so feel free to merge directly in case you agree with the approach.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1293"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Install compatible `cryptography` version

- app/license_notice.py
On Buster, the default Python version is 3.7, so our paths referenced that Python version. On Bullseye, the default Python version is 3.9, which broke our paths to third-party licenses.
This change changes the version to 3.* so that it will match any Python version. There's a risk that we'll match the wrong version package, but I think that's less likely than accidentally breaking links to licenses.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1300"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix paths to third-party licenses in Python 3.9 environments

- app/license_notice.py
- bundler/bundle/requirements.txt
Resolves https://github.com/tiny-pilot/tinypilot/issues/1299
The PR uses the [latest `cryptography` wheel available on Debian Buster](https://www.piwheels.org/project/cryptography/):
I've tested the [bundle](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3011/workflows/3f1380ee-79bf-4ae4-9490-6f4fb50e21b4/jobs/14269/artifacts) installation on a device running Raspberry Pi OS Lite Buster.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1303"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Downgrade to cryptography 37.0.4 wheel.

- CONTRIBUTING.md
Corresponds with: https://github.com/tiny-pilot/style-guides/pull/1
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1309"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Move style guide documentation to dedicated repo

- app/static/js/app.js
- app/static/js/keyboardstate.js
- app/static/js/keyboardstate.test.js
Resolves https://github.com/tiny-pilot/tinypilot/issues/361
Background:
For normal keys (i.e., non-modifier keys) we [automatically release the key after being pressed](https://github.com/tiny-pilot/tinypilot/blob/86fae61abb9502fe87d487c6f9da5abd7416c272/app/hid/keyboard.py#L10-L18). We don't do this for modifier keys, instead we wait for the "keyup" event to fire.
When a user presses `ALT+TAB` to change applications on their host machine, the "keydown" events would fire, but the "keyup" events do not fire because the focus has already been switched to a different application when the keys are eventually released. From the target machine's perspective, this causes the modifier keys to appear stuck.
To avoid this, we release any modifier keys currently being pressed once the browser window …
> Release modifier keycodes when browser window loses focus.

- .github/workflows/merge-pro.yml
Update the wording on the message team members see when we need to sync changes from Community to Pro:
* Make it clear that a human must take action to complete the process
* Make an accidental squash and merge less scary
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1324"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Clarify wording around syncing Community to Pro

- .circleci/config.yml
- ansible-role/files/init-usb-gadget
- ansible-role/files/lib/usb-gadget.sh
- ansible-role/files/remove-usb-gadget
- debian-pkg/opt/tinypilot-privileged/scripts/change-hostname
- debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip
- debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip
- dev-scripts/enable-mock-scripts
- get-tinypilot.sh
Also fix new bash lint that the new version picks up, mainly around `readonly`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1337"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Upgrade to shellcheck v0.9.0

- README.md
- ansible-role/meta/main.yml
- debian-pkg/Dockerfile
Resolves https://github.com/tiny-pilot/tinypilot/issues/1348
This PR is a non-functional change that replaces any mention of "buster", in documentation, with "bullseye".
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1358"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Declare Bullseye as the minimum supported version

- dev-scripts/enable-mock-scripts
We expect developers to run `enable-mock-scripts` using sudo, but we don't include our standard `EUID` check at the top of the file to prevent users from accidentally running without sudo. If the user runs the script without sudo, they'll likely hit a non-obvious error about file permissions.
This change adds an explicit check in `enable-mock-scripts ` that the developer executed it with sudo. If a developer runs the script without sudo permissions, they'll see a clear error message telling them to re-run with sudo.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1378"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Explicitly require sudo for enable-mock-scripts

- dev-scripts/check-trailing-whitespace
- dev-scripts/enable-mock-scripts
Our convention for messages printed to stderr is to omit any prefixes:
>Error messages don't have any prefixes like ERROR: or WARNING:.
https://github.com/tiny-pilot/style-guides#error-messages
To observe our style conventions more consistently, this change removes an "error" prefix from two error message.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1379"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove 'Error: ' prefix from stderr messages

- bundler/bundle/install
Resolves https://github.com/tiny-pilot/tinypilot/issues/1361#issuecomment-1522489669 (again 🤭)
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1380"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Limit installer's OS version check to Raspbian only

- bundler/README.md
- bundler/verify-bundle
- get-tinypilot.sh
- scripts/install-bundle
Resolves https://github.com/tiny-pilot/tinypilot/issues/1357
Blocked on https://github.com/tiny-pilot/tinypilot-pro/issues/775
To avoid excessive writes to the filesystem that could cause filesystem corruption, we now download and unpack the TinyPilot bundle to a temporary in-memory filesystem (i.e., RAMdisk).
1. The RAMdisk is mounted at `/mnt/tinypilot-installer`. This means that the installer directory (i.e., the directory where the bundle is unpacked to) has been changed from `/opt/tinypilot-updater` to `/mnt/tinypilot-installer`. I thought it would be best to namespace the mount point with "-installer" to not clash with future possible TinyPilot filesystems.
1. All files in the RAMdisk is removed when the filesystem is unmounted. So during the install clean-up we use [`umount …
> Perform updates/installs in RAMdisk

- .circleci/continue_config.yml
- ansible-role/test.txt
Resolves https://github.com/tiny-pilot/tinypilot/issues/1409
To avoid not testing the Ansible build for an extended period of time, we would rather opt for always building the Ansible role on the master branch.
Notes:
* I found an example of a similar CircleCI condition we were after, [here](https://discuss.circleci.com/t/advanced-logic-in-config/36011).
* I've tested that the Ansible role builds for the following conditions, separately:
* Test `branch == 'build-ansible-master'` condition https://github.com/tiny-pilot/tinypilot/pull/1410/commits/492f8a9d0b13f19efca3ccf814021d6248787e95
* Test `ansible_role_changed == True` condition https://github.com/tiny-pilot/tinypilot/pull/1410/commits/39e5f9fde35a4eb1e541122994db407152d37c0d
<a data-ca-tag …
> Always build Ansible role on master branch

- get-tinypilot.sh
- scripts/install-bundle
Resolves https://github.com/tiny-pilot/tinypilot/issues/1402
In order to accommodate users who want to install TinyPilot on devices with less than 500MB of RAM (i.e., Raspberry Pi Zero), the `get-tinypilot.sh` script now falls back to installing TinyPilot from disk if there isn't enough available memory to mount a RAMdisk.
Notes:
* The changes made to `get-tinypilot.sh` have also been copied over to the `scripts/install-bundle` script
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1406"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fall back to installing from disk when device has insufficient memory 

- ansible-role/molecule/default/molecule.yml
- ansible-role/vars/main.yml
Resolves https://github.com/tiny-pilot/ansible-role-ustreamer/issues/100
This PR specifies the URL to our [uStreamer Debian package release](https://github.com/tiny-pilot/ustreamer-debian/releases/tag/ustreamer_5.38-20230525134432) (via the `ustreamer_debian_package_path` variable) and avoids unnecessarily specifying uStreamer git variables (i.e., `ustreamer_repo` and `ustreamer_repo_version `) in the TinyPilot Ansible role. 
Notes:
* By default our Ansible role will install uStreamer for `armhf` architecture. However, to test the Ansible role in CI, we needed to [override the `ustreamer_debian_package_path` value to point to uStreamer for `amd64` architecture](https://github.com/tiny-pilot/tinypilot/pull/1408/files#diff-a820d54bd8941675036b81b0e7d1b08afee2821c526e5806ab6c8482ec0880d4R24-R …
> Install uStreamer via Debian package instead of building from source

- ansible-role/files/usb-gadget.service
- ansible-role/tasks/install_usb_gadget.yml
As part of the War on Ansible, I'd like to refactor a little bit how we place the usb-gadget systemd file.
We're unlikely to change the path of the TinyPilot privileged directory from the current `/opt/tinypilot-privileged`, so we should just hardcode it into the `usb-gadget` systemd file and save ourselves the extra Ansible logic of templating the file.
This will make it slightly easier to later port the systemd file into debhelper like we currently do with tinypilot-updater.
Tested on a Voyager 2a device.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1411"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Simplify placement of the usb-gadget service definition

- ansible-role/tasks/main.yml
In TinyPilot Pro, we recently made nginx the last step of the Ansible role (https://github.com/tiny-pilot/tinypilot-pro/pull/836), so this makes the parallel change in Community to keep the two repos aligned.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1413"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Make nginx install the last step of the Ansible role

- ansible-role/meta/main.yml
- ansible-role/tasks/install_usb_gadget.yml
We added this very early in the project (https://github.com/tiny-pilot/ansible-role-tinypilot/pull/77), and I don't think there are many users still on Ubuntu, if any.
We dropped Ubuntu support for ansible-role-ustreamer six months ago (https://github.com/tiny-pilot/ansible-role-ustreamer/pull/63), so I suspect that TinyPilot doesn't fully work on Ubuntu anyway.
This also simplifies the logic around writing to `/boot/config.txt` and `/etc/modules`, which are Raspbian-specific paths. We partially added conditional logic for writing to these files for CI and partly to accommodate non-Raspbian distros. If we're not supporting other distros, I think a simpler approach is to more explicitly skip these steps in CI (under molecule).
Removing Ubuntu support simplifies our Ansible logic and …
> Drop Ubuntu support from Ansible role

- ansible-role/tasks/install_usb_gadget.yml
- debian-pkg/debian/rules
- debian-pkg/debian/tinypilot.postinst
In continuing our War on Ansible, this strips the logic for enabling the dwc2 kernel driver (USB OTG functionality) from Ansible and reimplements it in the Debian install script.
I originally added a check to make sure we're installing on Raspbian to mirror the checks we were doing to avoid failing in molecule in CI, but I realized that if it's not a Raspbian system, the installer will just create the missing files, which isn't a problem.
I tested this by building a TinyPilot Pro microSD image with this branch and https://github.com/tiny-pilot/tinypilot/pull/1418:
https://github.com/tiny-pilot/tinypilot-pro/tree/debian-dwc2-scratch
On boot, the USB emulation functionality worked fine. `/boot/config.txt` and `/etc/modules` had the expected contents.
Then, I tried building an updated bundle …
> Enable the dwc2 driver from the Debian package install

- app/update/settings.py
- app/update/settings_test.py
In https://github.com/tiny-pilot/tinypilot/pull/1404 @jdeanwallace suggested consolidating the default values we need during update/install into `app/update/settings.py`.
I thought that was a good idea, so I'm doing a bit of refactoring of `app/update/settings.py` in preparation of that effort.
This is a pure refactoring and should have no functional effects outside of the `settings` module. We're changing the behavior of `as_dict`, but we don't call that outside of `settings`.
The idea of the change was that previously, we were avoiding saving any setting to the `Settings` object's internal dict if the value matched our defaults. The goal was to avoid writing out default values to the settings file because once we write them to the file, we can't tell if the user selected it explicitly …
> Refactor defaults in update settings

- ansible-role-ustreamer/tests/check-trailing-newline
Related https://github.com/tiny-pilot/tinypilot/issues/1426
Dependent on https://github.com/tiny-pilot/tinypilot/pull/1434
Caveat: This change is just to satisfy the [`check_bash` CI check](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3462/workflows/cd3bda98-6f98-4a4c-b860-0222cb4cf272/jobs/19191). We'll soon remove the `ansible-role-ustreamer/tests/check-trailing-newline` script entirely.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1436"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix shellcheck issues in ansible-role-ustreamer

- debian-pkg/debian/tinypilot.postinst
Per @jdeanwallace's comment (https://github.com/tiny-pilot/tinypilot/pull/1404#pullrequestreview-1479361539), there's a simpler way of generating the template file without having to bend around single quotes, so we should use it.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1441"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Simplify heredoc in TinyPilot postinst

- .circleci/continue_config.yml
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/931
This PR adds an additional `bundle_build_branch` CI pipeline parameter that specifies which branch triggers a build (i.e., running `build_debian_package`, `build_ansible_role`, and `build_bundle`). In TinyPilot Pro, this would eventually also create a microSD image.
We can now manually trigger a build with a one-line change https://github.com/tiny-pilot/tinypilot/pull/1442/commits/ea8b10e3c825fa002246c9a59c50c7ed58260c5d
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1442"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Easily trigger CI builds for testing/debugging

- .github/workflows/merge-pro.yml
Our Github workflow, that automatically creates a TinyPilot Pro PR with TinyPilot Community changes, has [started to fail](https://github.com/tiny-pilot/tinypilot/actions/runs/5280147817) because [Github Actions is deprecating Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR upgrades each of the Github Actions that we use to a version that supports Node 16.
Tested via https://github.com/tiny-pilot/tinypilot-pro/pull/938
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1447"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update Github Actions to a version that support Node 16

- ansible-role-ustreamer/tasks/install_launcher.yml
Resolves #1449
On Pi Zero W, Ansible detects the architecture as `armv6l`. This PR updates our mappings of Ansible-semantics to yq-semantics names of architectures to include a mapping of `armv6l` -> `arm`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1448"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add a yq binary mapping for armv6l

- get-tinypilot.sh
- scripts/install-bundle
Resolves https://github.com/tiny-pilot/tinypilot/issues/1461
Based on `man free` it is more appropriate to use the metric for available memory instead of free memory, when deciding whether to use the RAMdisk for TinyPilot installation/update.
>   free   Unused memory (MemFree and SwapFree in /proc/meminfo)
> ...
> available: Estimation of how much memory is available for starting new applications, without swapping. Unlike the data provided by the cache or free fields, this field  takes  into account  page cache and also that not all reclaimable memory slabs will be reclaimed due to items being in use (MemAvailable in /proc/meminfo, available on kernels 3.14, emulated on kernels 2.6.27+, otherwise the same as free)
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1463">< …
> Use RAMdisk based on available memory instead of free memory

- app/templates/custom-elements/menu-bar.html
- e2e/about.spec.js
- e2e/debug-logs.spec.js
This change adds four Accessible Rich Internet Applications (ARIA) roles to our menu bar. This allows us to use clearer semantics in our end-to-end tests and better present the UI to assistive technologies.
I largely based the role assignment on these examples:
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role#examples
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role#examples
>A menubar is a presentation of menu that usually remains visible and is usually presented horizontally.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menubar_role
I applied this to the top-level container for our menu.
I debated between `menubar` and `menu`, but `menubar` felt like the closer fit.
>The `menuitem` role …
> Add ARIA roles to menu bar elements

- .circleci/continue_config.yml
- ansible-role-ustreamer/tasks/main.yml
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/956
Related https://github.com/tiny-pilot/ustreamer-debian/issues/11
Related https://github.com/tiny-pilot/tinypilot/pull/1459
I accidently broke TinyPilot Pro image builder via https://github.com/tiny-pilot/tinypilot-pro/pull/955#issuecomment-1611870272
This PR is non-functional change that moves the provisioning of `tc358743` chip only until after the uStreamer Debian package is installed (and only after the `ustreamer` user has been created).
Notes:
1. I've [moved the TC358743 provisioning closer down to the uStreamer launcher tasks](https://github.com/tiny-pilot/tinypilot/blob/05f256fc6cac24ac62ec8a41a28e52cb9b2e5d15/ansible-role-ustreamer/tasks/main.yml#L112-L136) because the [TC358743 provisioning sets a bunch of ustreamer …
> Remove circular dependency on uStreamer user when provisioning tc358743 chip

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
Resolves #1432.
This change adds a new section to the debug logs listing all available network interfaces, including popular VPNs, virtual network devices, USB adapters, and so on, and their current active state:
```
Network interfaces:
eth0 (down)
lo0 (unknown)
wlan0 (up)
tailscale0 (up)
wg0 (down)
```
This addition will be helpful for support purposes, as we can see at a glance whether the user is connecting over something other than the onboard Ethernet.
Users may consider details of their network configuration to be sensitive. This conservative approach provides the most helpful information while ensuring we don't accidentally leak sensitive information.
I opted to use `/sys/class/net` rather than directly parsing the output of `ip` or `ifconfig`. The rationale for this decision is …
> Include network interface details in debug logs

- ansible-role-ustreamer/meta/main.yml
- ansible-role-ustreamer/tasks/install_janus.yml
- ansible-role-ustreamer/tasks/main.yml
- ansible-role-ustreamer/vars/Debian.yml
- ansible-role-ustreamer/vars/Ubuntu.yml
- ansible-role-ustreamer/vars/main.yml
We no longer support installing to Ubuntu, so we can drop Ubuntu-specific logic.
I tested this at the same time as #1477 by building a Pro bundle and installing it on a Voyager 2a.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1476"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Drop Ubuntu support for uStreamer

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
This change adds the state of the TinyPilot mouse jiggler to the debug logs under the TinyPilot state section.
We had one instance in the past where a hanging mouse jiggler caused issues with the mouse, so logging the state of our own mouse jiggler may help with debugging issues in the future.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1475"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Log whether the user is using the TinyPilot mouse jiggler

- ansible-role/defaults/main.yml
- ansible-role/vars/main.yml
Related https://github.com/tiny-pilot/tinypilot/issues/1429
This is non-functional change. This PR moves the definition of `tinypilot_interface` and `tinypilot_port` from `ansible-role/defaults/main.yml` to `ansible-role/vars/main.yml` which indicates that these variables should not be overridden.
This change is based on [our discussion](https://github.com/tiny-pilot/tinypilot/pull/1484#issuecomment-1622011263) about user-configurable variables:
> Currently, our convention is:
> * `defaults/` - Maybe we support users overriding these variables.
> * `vars/` - We definitely don't support users overriding these variables.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1492"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" …
> Mark certain Ansible variables as not user-configurable

- app/update/settings.py
- app/update/settings_test.py
Related https://github.com/tiny-pilot/tinypilot/issues/1429
This PR adds `tinypilot_external_port` to our dictionary of default TinyPilot settings. This is needed in order to use `tinypilot_external_port` in TinyPilot's NGINX config template via https://github.com/tiny-pilot/tinypilot/pull/1469
Notes:
1. This PR was triggered based on [our discussion](https://codeapprove.com/pr/tiny-pilot/tinypilot/1469#thread-03723286-15ac-4bb6-b466-86223f9b94c0) about user-configurable variables.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1497"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add TinyPilot's external port as a default TinyPilot setting

- ansible-role/README.md
- ansible-role/tasks/nginx.yml
- ansible-role/templates/tinypilot.systemd.j2
- ansible-role/vars/main.yml
Related https://github.com/tiny-pilot/tinypilot/issues/1429
This PR removes the `tinypilot_interface` Ansible variable and inlines its value (i.e., `127.0.0.1`) because TinyPilot should always only serve local connections.
As suggested by https://github.com/tiny-pilot/tinypilot-pro/issues/972, `tinypilot_interface` is considered a junk unsupported variable:
> We can either delete them because they're unused, or we can trivially inline their values because they're only used in one place.
Notes:
1. This PR was triggered based on [our discussion](https://codeapprove.com/pr/tiny-pilot/tinypilot/1469#thread-03723286-15ac-4bb6-b466-86223f9b94c0) about user-configurable variables.
2. You can test this PR via https://github.com/tiny-pilot/tinypilot/pull/1499
<a data-ca-tag …
> Drop tinypilot_interface Ansible variable

- .circleci/continue_config.yml
- ansible-role/README.md
- ansible-role/tasks/nginx.yml
- ansible-role/templates/tinypilot.systemd.j2
- ansible-role/vars/main.yml
Related https://github.com/tiny-pilot/tinypilot/issues/1429
Similar to https://github.com/tiny-pilot/tinypilot/pull/1498, this PR removes the `tinypilot_port` Ansible variable and inlines its value (i.e., `8000`).
As suggested by https://github.com/tiny-pilot/tinypilot-pro/issues/972, `tinypilot_port` is considered a junk unsupported variable:
> We can either delete them because they're unused, or we can trivially inline their values because they're only used in one place.
You can test this PR and https://github.com/tiny-pilot/tinypilot/pull/1498 by running the following command on device:
```bash
sudo /opt/tinypilot/scripts/install-bundle \
https://output.circle-artifacts.com/output/job/2e7b1af1-8c3b-4c04-8c26-bf52e82819e7/artifacts/0/bundler/dist/tinypilot-community-20230710T1448Z-1.9.0- …
```
> Drop tinypilot_port Ansible variable

- .circleci/continue_config.yml
- ansible-role/molecule/requirements.txt
- app/license_notice.py
- bundler/bundle/requirements.txt
- requirements.txt
Resolves https://github.com/tiny-pilot/tinypilot/issues/1507
The release of [Cython `3` broke PyYAML `5.4`](https://github.com/yaml/pyyaml/issues/724). This PR upgrades to PyYAML `6.0.1` which pins `Cython < 3.0.0`. 
Notes
1. While bootstrapping the molecule testing environment, it was [complaining about the following dependency conflict](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3695/workflows/1e8382a7-5a08-4a64-a87a-a5af41916c70/jobs/22051?invite=true#step-105-155):
```bash
The conflict is caused by:
The user requested PyYAML==6.0.1
molecule 3.2.3 depends on PyYAML<6 and >=5.1
```
So based on [someone's suggestion from the original GitHub issue](https://github.com/yaml/pyyaml/issues/724#issuecomment-1639872845), I pinned `pyyaml` to version `5.3.1`. However, I only …
> Upgrade to PyYAML 6.0.1

- app/static/502.html
This change turns the 502 error page into a self-serve troubleshooting page for users. When a user sees the page, they can follow the troubleshooting steps instead of posting on the forum.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1514"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Backport 502 improvements to Community

- .circleci/continue_config.yml
- ansible-role-ustreamer/defaults/main.yml
- ansible-role-ustreamer/files/launch
- ansible-role-ustreamer/tasks/install_launcher.yml
- ansible-role/vars/main.yml
- app/update/settings.py
- app/update/settings_test.py
- debian-pkg/usr/share/tinypilot/templates/tinypilot.conf.j2
Related https://github.com/tiny-pilot/tinypilot/issues/1431
In one of our dev meetings we mentioned that the `ustreamer_interface` Ansible variable can be dropped and the value inlined because uStreamer already serves on `127.0.0.1` by default.
Additionally, in https://github.com/tiny-pilot/tinypilot/issues/1431, we refactor `ustreamer_interface` from `ansible-role/vars/main.yml` to the end of `ansible-role-ustreamer/vars/main.yml`. To avoid doing this, we decided to drop `ustreamer_interface` instead.
In https://github.com/tiny-pilot/tinypilot-pro/issues/972, `ustreamer_interface` is considered an unsupported variable, which means:
> As we refactor to get rid of Ansible, we should make it impossible for users to override these values in `/home/tinypilot/settings.yml`
You can test this PR …
> Drop ustreamer_interface Ansible variable

- requirements.txt
Related https://github.com/tiny-pilot/tinypilot/issues/1026#issuecomment-1650368355
> Might as well be on latest and greatest.
This PR upgrades [`flask-socketio`](https://github.com/miguelgrinberg/Flask-SocketIO/tree/v5.3.4) to the latest version (5.3.4).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1526"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Upgrade flask-socketio to version 5.3.4

- .circleci/config.yml
- ansible-role-ustreamer/molecule/default/molecule.yml
- ansible-role-ustreamer/tasks/main.yml
- ansible-role-ustreamer/vars/main.yml
Resolves https://github.com/tiny-pilot/tinypilot/issues/1467
This change sets the correct permissions of the uStreamer directory (i.e., /opt/ustreamer) using the uStreamer Debian package, instead of using Ansible.
To test this bundle, run:
```bash
curl \
--silent \
--show-error \
--location \
https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
sudo bash -s -- \
https://output.circle-artifacts.com/output/job/e81ad09e-33d3-4703-a812-59bb58f415c2/artifacts/0/bundler/dist/tinypilot-community-20230802T1810Z-1.9.0-43+0d9bfb3.tgz
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1546"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Migrate uStreamer directory permissions to the uStreamer Debian package

- .circleci/config.yml
- .circleci/continue_config.yml
- CONTRIBUTING.md
Resolves https://github.com/tiny-pilot/tinypilot/issues/1548
This PR moves the comments that explains how to trigger a code-based bundle build from `.circleci/config.yml` to `.circleci/continue_config.yml` and updates the contributing docs to reference the correct CircleCI config file.
So the correct ways to [manually trigger a bundle build](https://github.com/tiny-pilot/tinypilot/blob/1ea663b0ee6679e0ab73e59f57de94e4b8e8a708/CONTRIBUTING.md#installing-a-nightly-bundle) is either the:
1. Code-based way
> 1. In [the CircleCI configuration](/.circleci/continue_config.yml), change the `bundle_build_branch` parameter’s `default` value from `master` to `<< pipeline.git.branch >>`.
> 1. Push your changes as branch to GitHub. CircleCI will now automatically build bundles for all subsequent …
> Fix instructions on how to manually trigger a bundle build

- .circleci/config.yml
This was supposed to resolve this https://github.com/tiny-pilot/tinypilot/issues/1559, but it wasn't actually related.
Might as well upgrade `circleci/path-filtering` while we're here.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1560"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Upgrade circleci/path-filtering to version 1.0.0

- ansible-role-ustreamer/files/launch
- ansible-role-ustreamer/tasks/install_launcher.yml
- ansible-role-ustreamer/vars/main.yml
- app/update/settings.py
- app/update/settings_test.py
- bundler/bundle/install
- debian-pkg/usr/share/tinypilot/templates/tinypilot.conf.j2
Related https://github.com/tiny-pilot/tinypilot/issues/1551
In https://github.com/tiny-pilot/tinypilot/pull/1562, we're moving uStreamer from port `8001` to port `48001`. However, before we do that I thought it might be a good time to hardcode the port number and <s>enforce non-user-configurability</s> drop the use of the `ustreamer_port` Ansible variable.
According to https://github.com/tiny-pilot/tinypilot-pro/issues/972, `ustreamer_port` is already considered a non-user-configurable variable. This PR enforces `ustreamer_port` as being non-user-configurable.
This PR does the following:
* Reverts https://github.com/tiny-pilot/tinypilot/pull/1493
(which introduced that `_CONSTANTS` variable in `app/update/settings.py`)
* Hardcodes the uStreamer port to `8001` in the TinyPilot NGINX config …
> Drop the use of the uStreamer port Ansible variable

- .circleci/continue_config.yml
`create-bundle` [used to depend on git](https://github.com/tiny-pilot/tinypilot/blob/1.8.0/bundler/create-bundle), as it downloaded external roles using git and used `git` to pull version information about the local repo.
We've since simplified the bundle build process, so we no longer require git, and we can delete the CI step when we install git into the container. This saves us about 5s on every bundle build in CI.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1564"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Skip installing git in build_bundle CI step

- ansible-role-ustreamer/tasks/main.yml
Resolves https://github.com/tiny-pilot/tinypilot/issues/1567
WebRTC audio streaming stopped working since https://github.com/tiny-pilot/tinypilot/pull/1470. The problem was that the uStreamer Janus plugin config file was being written before populating the `ustreamer_capture_device` variable, which resulted in no Janus audio config:
https://github.com/tiny-pilot/tinypilot/blob/b379ac26ea87a99e6126b3d616648b905013cb2f/ansible-role-ustreamer/templates/janus.plugin.ustreamer.jcfg.j2#L5-L10
The `ustreamer_capture_device` variable is populated when reading the `/home/ustreamer/config.yml` file:
https://github.com/tiny-pilot/tinypilot/blob/b379ac26ea87a99e6126b3d616648b905013cb2f/ansible-role-ustreamer/tasks/check_saved_settings.yml#L11-L14
Back in …
> Populate uStreamer Janus plugin config after reading capture device

- ansible-role-ustreamer/defaults/main.yml
As of 710ed072e9b048c1c2c953052c07656c9d58a24d, we no longer honor this variable, so we can safely delete it.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1569"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Delete dead ustreamer_port var

- .circleci/continue_config.yml
- ansible-role-ustreamer/defaults/main.yml
- ansible-role-ustreamer/files/launch
- ansible-role-ustreamer/handlers/main.yml
- ansible-role-ustreamer/tasks/install_launcher.yml
- ansible-role-ustreamer/tasks/main.yml
- ansible-role-ustreamer/tasks/provision_tc358743.yml
- ansible-role-ustreamer/templates/janus.plugin.ustreamer.jcfg.j2
- ansible-role-ustreamer/vars/main.yml
Resolves #1570
This change removes uStreamer variables in the Ansible role and hardcodes them. We now also unconditionally install Janus.
To test this bundle, run:
```bash
curl \
--silent \
--show-error \
--location \
https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
sudo bash -s -- \
https://output.circle-artifacts.com/output/job/8025923f-9ba2-4e45-aef0-952f0f12655b/artifacts/0/bundler/dist/tinypilot-community-20230824T1222Z-1.9.0-62+3908e48.tgz
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1585"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Hardcode h264 parameters

- debian-pkg/debian/tinypilot.postinst
There was a bug in the tinypilot.postinst where we were appending to an existing janus.plugin.ustreamer.jcfg file instead of the intended behavior of recreating the file fresh on each install.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1615"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Prevent tinypilot.postinst from appending to Janus config

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1030.
Raspberry Pi OS now updates the kernel on 32-bit installations to the 64-bit kernel while simultaneously keeping the userland as 32-bit, which means that it isn't possible to accurately determine if the user is running a 64-bit system based on the output of `uname --all`.
This change adds additional information to the `collect-debug-logs` script, allowing us to detect when a user is running TinyPilot on an unsupported architecture. It also slightly reformats the relevant section for readability.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1611"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update collect-debug-logs script to include userland architecture

- app/static/js/webrtc-video.js
- app/templates/custom-elements/remote-screen.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1487
This PR refactors our remote-screen WebRTC API to allow media tracks to be added/removed without automatically enabling/disabling the WebRTC streaming mode. This gives more responsibility to the (function) caller, but also gives more control in deciding when to change streaming modes.
Demo video:
https://github.com/tiny-pilot/tinypilot/assets/6730025/d891fbcb-1cea-41fe-b775-948b5a9879e6
Notes
1. We've renamed `enableWebrtcStreamTrack` -> `addWebrtcStreamTrack`
* This method no longer enables WebRTC mode (i.e., shows the video element)
1. We've renamed `disableWebrtcStreamTrack` -> `removeWebrtcStreamTrack`
* This method no longer disables WebRTC mode (i.e., hides the video element)
1. WebRTC mode can now both be enabled and have …
> Maintain h.264 video stream when target machine is switched off

- bundler/bundle/install
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/1074
This PR runs `apt-get update` before installing our Debian packages to ensure that the APT package index is up-to-date.
I have tested this fix in TinyPilot Pro:
* https://github.com/tiny-pilot/tinypilot-pro/pull/1075
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1623"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update apt package lists before install

- bundler/create-bundle
- debian-pkg/debian/tinypilot.postinst
- debian-pkg/usr/share/tinypilot/janus.service
Resolves https://github.com/tiny-pilot/tinypilot/issues/1578
This PR overrides the default Janus systemd config in order set additional systemd settings. Specifically:
```diff
[Unit]
Description=Janus WebRTC gateway
After=network.target
Documentation=https://janus.conf.meetecho.com/docs/index.html
+# Give up if we restart on failure 20 times within 5 minutes (300 seconds).
+StartLimitIntervalSec=300
+StartLimitBurst=20
[Service]
Type=forking
ExecStart=/usr/bin/janus --disable-colors --daemon --log-stdout
Restart=on-failure
+RestartSec=1
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
```
Janus with STUN requires the network to be online, otherwise `janus` fails to start. Theses additional settings are needed to allow Janus with STUN settings a better chance of starting up …
> Override Janus systemd config

- .pylintrc
- app/request_parsers/errors.py
- app/update/settings.py
- app/update_logs_test.py
- dev-scripts/build-python
- dev_requirements.txt
Add the pylint-quotes pylint plugin to the build to ensure we use consistent string quoting conventions throughout our Python code.
We had a few stray instances of inconsistent strings, so I fixed them in this change as well.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1628"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Enforce consistent string quoting rules

- app/templates/custom-elements/update-dialog.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1466
When updating TinyPilot via the web UI, if you're watching the detailed update logs it's easy to miss when the update has actually completed.
This PR adds the following messages to the update-dialog's update logs:
> Restarting to complete update...
> Update is now complete.
Demo video:
https://github.com/tiny-pilot/tinypilot/assets/6730025/378c0a23-f02e-4bae-a2d7-1113a12891c1
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1627"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Log message when update is complete

- app/hid/keyboard.py
- app/hid/keyboard_test.py
- app/hid/keycodes.py
- app/js_to_hid.py
- app/js_to_hid_test.py
- app/socket_api.py
Related https://github.com/tiny-pilot/tinypilot/issues/1026
This PR introduces the HID `Keystroke` class that represents a combination of HID keycode and HID modifier. This PR replaces the use of individual `keycode` and `modifier`/`control_keys` variables with a single `keystroke` variable.
This is a non-functional change that simplifies the way we represent HID Keystrokes in anticipation for parsing text to HID keystrokes via https://github.com/tiny-pilot/tinypilot/pull/1624
1. In https://github.com/tiny-pilot/tinypilot/pull/1625, we parse `text` + `language` directly to HID keystrokes in a [`request_parser`](https://github.com/tiny-pilot/tinypilot/blob/df246c830564eb164b9206d9ea9b0cfc6ae4e248/app/request_parsers/paste.py#L6-L44). Ideally, I'd like to do the same when [parsing JS …
> Add HID Keystroke class

- bundler/bundle/install
In #776, we added the `--allow-releaseinfo-change-suite` to avoid erroring out if the Raspbian apt repo changed suite names.
In #1604, we deleted the `apt update` command entirely, as it seemed unnecessary after deleting Ansible.
In #1623, we brought back the `apt update` command, but we left off the  flag we were previously using.
In recent installs, I'm seeing this warning:
```bash
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Repository 'http://raspbian.raspberrypi.org/raspbian bullseye InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
Reading package lists... Done
```
For the sake of preserving longstanging behavior, I think we should bring back the `--allow-releaseinfo-change-suite` flag.
<a data-ca-tag …
> Bring back --allow-releaseinfo-change-suite

- .pylintrc
- .ruff.toml
- dev-scripts/build-python
- dev_requirements.txt
ruff can replicate the same functionality as pylint-quotes but with faster performance and fewer extra tools, so this replaces pylint-quotes with ruff.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1635"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Replace pylint-quotes with ruff

- .circleci/config.yml
- dev-scripts/run-e2e-tests
- dev-scripts/serve-dev
Currently, the end-to-end test reuses the dev database in `~/tinypilot.db`. But that means that a DB corruption in one test run will affect subsequent runs, which we don't want.
To fix this, we can adjust the `run-e2e-test` script to use a temporary directory as TinyPilot's home directory for storing the TinyPilot SQLite database.
We also adjust the CI code so that it more closely matches the dev workflow.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1637"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use a fresh database on each e2e test run

- bundler/create-bundle
Note that the change in the URL path outside the version + timestamp is due to a mistake in how we generated the release tag for the previous uStreamer Debian package: 
https://github.com/tiny-pilot/ustreamer-debian/tree/ustreamer_5.38-20230802141939
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1643"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update uStreamer package to v5.43

- app/templates/custom-elements/update-dialog.html
- app/version.py
Resolves #1503.
This change adds code to intercept `CERTIFICATE_VERIFY_FAILED` errors that have a reason of "certificate is not yet valid" when checking for updates so the app can show a more actionable error message. Any other type of certificate or URL error is unaffected.
You can test the change by turning off the network time service and then setting the date back by a few years:
```bash
sudo systemctl stop systemd-timesyncd
sudo date --set='-2 years'
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1653"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Improve error messaging when updates fail due to an incorrectly set clock

- app/templates/custom-elements/menu-bar.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1641
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1067
Menu bar:
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1664"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Move Hostname menu-item to Networking submenu

- app/cli.py
- app/main.py
- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
- scripts/streaming-mode
Resolves https://github.com/tiny-pilot/tinypilot/issues/1490
Video demo:
https://github.com/tiny-pilot/tinypilot/assets/6730025/0165c85d-f9fa-4389-b98d-44de90843f5a
1. When there are active WebRTC consumers, I see this in the Janus logs:
```
Oct 30 15:27:57 tinypilot janus[1790]: Creating new session: 3545622190134115; 0xed914e28
Oct 30 15:27:57 tinypilot janus[1790]: Creating new handle in session 3545622190134115: 8464226001965214; 0xed914e28 0xefb019c8
Oct 30 15:27:57 tinypilot janus[1790]: == ustreamer/main      -- Creating session 0xefb01650 ...
Oct 30 15:27:57 tinypilot janus[1790]: == ustreamer/video     -- Memsink opened; reading frames ...
Oct 30 15:27:57 tinypilot janus[1790]: [8464226001965214] Creating ICE agent (ICE Full mode, controlling)
Oct 30 15:27:57 tinypilot …
```
> Add video streaming mode to TinyPilot logs

- bundler/bundle/install
Resolves #1667.
TinyPilot doesn't currently work on Raspberry Pi OS Bookworm, so this change adds a check to prevent installation on versions of Raspberry Pi OS newer than Bullseye. A link to the [issue for adding Bookworm support](https://github.com/tiny-pilot/tinypilot/issues/1668) is included in the error message for convenience. I've tested this on-device on both Bullseye and Bookworm.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1671"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Prevent installation on Bookworm

- .circleci/config.yml
- CONTRIBUTING.md
- dev_requirements.txt
I recently discovered that you can have a requirements.txt file include another requirements.txt file, so I thought it would be useful to take advantage of this and simplify some of our dev workflows.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1681"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Implicitly install requirements.txt when installing dev_requirements.txt

- app/static/js/app.js
- app/static/js/keyboardstate.js
- app/static/js/keyboardstate.test.js
Related https://github.com/tiny-pilot/tinypilot/issues/1167
This PR fixes a minor bug in our keyboard state of currently pressed keys. I discovered this issue while exploring https://github.com/tiny-pilot/tinypilot/pull/1703.
The issue was that when I press <kbd>Meta</kbd> + <kbd>L</kbd> in chrome, the focus switches to the address bar and I release all keys, but the keyboard state still thinks `KeyL` is pressed.
I used https://github.com/tiny-pilot/tinypilot/pull/1705 to investigate the keyboard state.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1706"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix keyboard state when browser window loses focus

- app/templates/custom-elements/key.html
- app/templates/custom-elements/on-screen-keyboard.html
Related https://github.com/tiny-pilot/tinypilot/issues/1167
This PR simplifies the on-screen keyboard by removing redundant `modifier="true"` attribute and `modifier` class. The on-screen keyboard now only relies on the `isModifierCode` helper function as the single source of truth.
This PR is a non-functional change.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1704"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove modifier attributes from on-screen keyboard keys

- debian-pkg/debian/tinypilot.load-tc358743-edid.service
Resolves https://github.com/tiny-pilot/tinypilot/issues/1726
This PR only starts the `load-tc358743-edid.service` when a TC358743 capture chip is installed. This change avoids reporting the service as "failed" when a TC358743 capture chip is not installed on the device.
**Caveat:** The `load-tc358743-edid.service` process is still marked as `(code=exited, status=1/FAILURE)`, but it's active state is no longer `failed (Result: exit-code)`. Instead, its active state is `inactive (dead) (Result: exec-condition)`.
Example output of service being skipped:
```
Jan 28 18:41:02 raspberrypi systemd[1]: Starting Load EDID for TC358743 HDMI capture chip....
Jan 28 18:41:02 raspberrypi systemd[1]: load-tc358743-edid.service: Control process exited, code=exited, status=1/FAILURE
Jan 28 18:41:02 …
```
> Conditionally load EDID on device with TC358743 capture chip

- debian-pkg/debian/tinypilot.postinst
- debian-pkg/opt/tinypilot-privileged/scripts/configure-janus
- scripts/render-template
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/1190
Please refer to https://github.com/tiny-pilot/tinypilot-pro/issues/1190#issue-2094765706 for PR rationale.
Executing the `render-template` script with root privileges with now fail. For example, as part of the TinyPilot installation:
```bash
$ apt-get install -y ./tinypilot_20240128105411_armhf.deb
...
Preparing to unpack .../tinypilot_20240128105411_armhf.deb ...
Unpacking tinypilot (20240128105411) over (20240128094116) ...
Setting up tinypilot (20240128105411) ...
Warning: The home dir /home/tinypilot you specified already exists.
The system user `tinypilot' already exists. Exiting.
/opt/tinypilot /
This script doesn't require root privileges.
Please re-run as tinypilot:
runuser tinypilot --command …
```
> Add privilege check to render-template script

- app/static/js/hostname.js
- app/static/js/hostname.test.js
- app/templates/custom-elements/change-hostname-dialog.html
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1162
Resolves https://github.com/tiny-pilot/tinypilot/issues/771
This PR refactors the `futureLocation` function to `app/static/js/hostname.js` and renames it to `determineFutureOrigin`. This change is needed to allow the function to be reused by https://github.com/tiny-pilot/tinypilot-pro/pull/1169
This is mostly a non-functional change with the following caveats:
1. Name change
* Before
`futureLocation`
* After
`determineFutureOrigin`
3. Docstring change
* Before
https://github.com/tiny-pilot/tinypilot/blob/34161c3c450f5bc3c99cffbd3cd0a778aaeed6dd/app/templates/custom-elements/change-hostname-dialog.html#L100-L107
* After
https://github.com/tiny-pilot/tinypilot/blob/d889c24044a510a5ba91464ac229dcd3c08bd578/app/static/js/hostname. …
> Refactor hostname helper function

- CONTRIBUTING.md
Related to (and stacked on) https://github.com/tiny-pilot/tinypilot/pull/1736, I thought we could also add a style guide reference to the CONTRIBUTING doc.
Note that we are not consistent with title case vs. non-title case for headlines in that CONTRIBUTING doc. Most headlines  don’t seem to use it, so I’ve followed that for consistency.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1737"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Reference style guide from CONTRIBUTING doc

- CONTRIBUTING.md
- app/templates/styleguide.html
I realized we don't really explain how the user should view the style guide, so I added a brief comment on the top explaining how to view the style guide in the browser.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1736"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add instructions for viewing style guide

- .github/ISSUE_TEMPLATE/bug_report.md
Resolves #1732 
This change updates the bug template to fix the command for collecting a log, add instructions for retrieving a log on the TinyPilot web interface, and add a section asking for video capture hardware (if applicable).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1740"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Revise bug template for better feedback

- README.md
- get-tinypilot.sh
- scripts/upgrade
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1214
Based on our efforts to mitigate privilege escalation, the `scripts/upgrade` script was identified as both tinypilot-writeable and requiring root privileges. However, this script is now considered legacy and can be removed because [it was only needed at a time when TinyPilot could only be updated via the terminal](https://codeapprove.com/pr/tiny-pilot/tinypilot/1743#thread-5433ea94-c337-4b07-a1cd-20651c032dd5).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1744"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove legacy upgrade script

- .circleci/config.yml
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1229
In an effort to reduce repetition on our CircleCI config, this PR defines standard CircleCI `executors` instead of redefining them on every job.
Notes:
1. FYI, CircleCI's `cimg/base` is an Ubuntu image:
> `cimg/base` is an Ubuntu Docker image created by CircleCI with continuous integration builds in mind. As its name suggests, this image is designed to serve as a base image for other CircleCI Convenience Images (images prefixed with cimg/).
1. This means that most jobs would use the same base image and are now being upgraded to the latest available image (i.e., `cimg/base:2024.02`)
- <s>We can't upgrade the base images on all jobs because some rely on very specific versions. For example: …
> Define standard CircleCI executors

- .circleci/config.yml
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1229
In an effort to reduce repetition on our CircleCI config, this PR includes the following:
* Ports our [environment variable check from Tinypilot Pro](https://github.com/tiny-pilot/tinypilot-pro/blob/bddd86133a6685cef3ddc43631359ee97181d509/.circleci/config.yml#L273-L285).
- Less one environment variable we don't use in Community.
* Introduces the env check as a reusable CircleCI command.
* We do this because in pro we make use of the env check more than once.
1. https://github.com/tiny-pilot/tinypilot-pro/blob/bddd86133a6685cef3ddc43631359ee97181d509/.circleci/config.yml#L273-L285
2. https://github.com/tiny-pilot/tinypilot-pro/blob/bddd86133a6685cef3ddc43631359ee97181d509/.circleci/config.yml#L335-L347
<a data-ca-tag …
> Add CircleCI command that checks a project's environment variables

- .circleci/config.yml
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/1260
<s>We need to make the following changes in CircleCI:
1. Create a CircleCI secure context for TinyPilot Community.
1. Open the [TinyPilot CircleCI context](https://app.circleci.com/settings/organization/github/tiny-pilot/contexts)
1. Click "Create Context"
1. Enter a context name:
* Perhaps we should name it `community-production`?
1. Click "Create Context"
1. Restrict the TinyPilot Community context to only be used on the `master` branch and when SSH is disabled on the CI job.
1. Click the TinyPilot Community context
1. Click "Add Expression Restriction"
1. Enter the following expression in the text box:
* `pipeline.git.branch == "master" and not job.ssh.enabled`
1. Click "Add Expression Restriction"
1. Add new production …
> Use CircleCI secure context when uploading bundle to Backblaze

- README.md
The preferred way for users to update TinyPilot is via System > Update in the web UI.
The old CLI method still worked, but it's not how we want to encourage users to update, so we should remove this section of the README.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1757"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove instructions for updating from the command-line

- .github/workflows/merge-pro.yml
Since https://github.com/tiny-pilot/tinypilot-pro/pull/1265#pullrequestreview-1949780397, we've added a review-requirement to the `tinypilot-pro` repo.
This PR updates the automatic community PR description to mention that we need to review the changes ourselves before merging.
Notes:
* I've also updated the description to @mention the author
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1756"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update automatic Community PR description to mention self-review step

- CONTRIBUTING.md
- app/templates/custom-elements/button-dropdown.html
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/feature-pro-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/paste-dialog.html
- app/templates/custom-elements/remote-screen.html
- app/templates/custom-elements/share-logs-button.html
- app/templates/custom-elements/update-dialog.html
- app/templates/custom-elements/video-settings-dialog.html
- app/templates/custom-elements/video-settings-h264-stun.html
Related https://github.com/tiny-pilot/tinypilot/issues/1120
This is non-functional change.
Notes
* Pattern matched: `this\.elements(?=\W)`
Replaced with: `this._elements`
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1758"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Rename private elements field with underscore prefix 

- dev-scripts/run-e2e-tests
Resolves https://github.com/tiny-pilot/tinypilot/issues/1696
This PR allows for extra Playwright CLI options to passed to Playwright when running e2e tests.
For example, this means you can guide Playwright on which tests to run like so: 
```bash
./dev-scripts/run-e2e-tests -- --grep 'shows privacy policy'
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1768"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Allow for extra Playwright CLI options when running e2e tests

- docs/user-configurable-settings.md
Resolves https://github.com/tiny-pilot/tinypilot/issues/1573
Since winning the war on Ansible, we've dropped support for many TinyPilot settings that were configurable via `/home/tinypilot/settings.yml`.
Apart from this blog post ([/whats-new-in-2022-05/](https://github.com/tiny-pilot/tinypilotkvm.com/blob/ba842c50235005fb9253e316cf4f85a543548634/content/blog/whats-new-in-2022-05/index.md)) we haven't really documented (publicly) which settings are supported, deprecated, and unsupported. This PR does just that:
* Document preview: [docs/user-configurable-settings.md](https://github.com/tiny-pilot/tinypilot/blob/document-user-configurable-settings/docs/user-configurable-settings.md)
1. The list of [supported settings](https://github.com/tiny-pilot/tinypilot/blob/document-user-configurable-s …
> Document user configurable settings

- CONTRIBUTING.md
Resolves: #1797 
Related: https://github.com/tiny-pilot/ustreamer-debian/issues/17
This change removes references to amd64 ustreamer Debian package builds in CircleCI now that CI only uses an ARM executor. 
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1798"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update CONTRIBUTING docs to no longer say that we build amd64 Debian ustreamer packages

- .circleci/config.yml
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1319
This change in needed so that we don't rely the custom `koalaman/shellcheck-alpine` docker image, which might not include some standard packages that we rely on (like `curl`).
Notes:
1. This is the community PR of this Pro PR:
* https://github.com/tiny-pilot/tinypilot-pro/pull/1321
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1800"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use ubuntu CI executor when checking bash scripts

- e2e/about.spec.js
Resolves #1751
This change fixes the license link tests that fail when running using HTTPS on a live device.
Instead of using `fetch`, the new test uses Playwright's `page.goto` to check for a 200 response from each license URL.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1806"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix About dialog e2e license link tests

- debian-pkg/opt/tinypilot-privileged/scripts/change-hostname
Resolves #1679
This change updates the `change-hostname` script to use `hostnamectl` instead of editing `/etc/hostname` directly.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1803"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update change-hostname to use hostnamectl

- debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs
- debian-pkg/opt/tinypilot-privileged/scripts/print-marker-sections.bats
- debian-pkg/opt/tinypilot-privileged/scripts/read-update-log
- debian-pkg/opt/tinypilot-privileged/scripts/strip-marker-sections.bats
- dev-scripts/check-privilege-guard
- dev-scripts/device/install-bundle
- dev-scripts/enable-mock-scripts
- dev-scripts/enable-passwordless-sudo
- scripts/is-ssh-enabled
- scripts/streaming-mode
Resolves https://github.com/tiny-pilot/tinypilot/issues/1780
This PR align our bash scripts with the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html#s6.9-arithmetic):
> For preference, don’t use `[[ … ]]` at all for numeric comparisons, use `(( … ))` instead.
Notes:
1. I've replaced numerics checks using `[[ -ne ]]` with `(( != ))`
2. I've replaced numerics checks using `[[ == ]]` with `(( == ))`
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1836"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Use bash arithmetic checks

- CONTRIBUTING.md
- app/static/js/app.js
- app/templates/custom-elements/about-dialog.html
- app/templates/custom-elements/change-hostname-dialog.html
- app/templates/custom-elements/debug-dialog.html
- app/templates/custom-elements/network-status-dialog.html
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/paste-dialog.html
- app/templates/custom-elements/video-settings-dialog.html
- app/templates/custom-elements/wifi-dialog.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1773
This PR replaces the `overlay-toggled` event with two separate `overlay-shown`/`overlay-hidden` events and fires them into the slotted (dialog) element which allows slotted custom components to initialize themselves when the dialog is shown. For example:
```javascript
connectedCallback() {
// ...
this.addEventListener("overlay-shown", () => {
this._state = this._states.INITIALIZING;
});
}
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1835"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Unify initialization procedure of dialogs

- app/templates/custom-elements/about-dialog.html
While working on https://github.com/tiny-pilot/tinypilot/pull/1835, I noticed a bug in the "About" dialog where the list of credits keep growing each time the dialog gets opened.
Demo of the issue:
https://github.com/user-attachments/assets/dd4cb4e9-9406-4d50-b42f-149684181d7b
This PR clears the credits before populating them.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1840"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Clear about page credits before populating them

- app/static/css/style.css
- app/static/js/events.js
- app/templates/custom-elements/overlay-panel.html
- app/templates/custom-elements/shutdown-dialog.html
- app/templates/custom-elements/update-dialog.html
- app/templates/custom-elements/wifi-dialog.html
- app/templates/styleguide.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1639
Based on a [PR review discussion](https://codeapprove.com/pr/tiny-pilot/tinypilot/1833#thread-59475250-2fc2-4e74-9b4f-359067e9a3c8), this PR adds an event (i.e., `DialogVariantChangedEvent`) that allows us to change the dialog's visual variant style in order to make it more engaging for the user.
For example, we can now change the dialog variant when a successful state is reached:
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1841"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add a success dialog variant

- app/static/js/app.js
- app/templates/custom-elements/menu-bar.html
Resolves https://github.com/tiny-pilot/tinypilot/issues/1838.
Related https://github.com/tiny-pilot/tinypilot/issues/481.
This change adds the following additional keyboard shortcuts:
- Ctrl+Alt+Backspace - Restart the desktop environment on Linux.
- Meta+Alt+Escape - Open the "Force Quit" utility on macOS.
- Alt+Tab - Switch to the next window on macOS, Windows, and more.
I've mimicked the approach of sending one key at a time used by the existing Ctrl+Alt+Delete shortcut to more accurately represent how a user would enter these shortcuts on a physical keyboard.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1839"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add additional keyboard shortcuts

- app/templates/custom-elements/wifi-dialog.html
Resolves #1852
This change removes the second colon in the Wi-Fi dialog when it warns there's no Ethernet connection.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1853"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix typo in WiFi dialog

- README.md
Resolves #1855
This change updates our README to be more clear with installation requirements. The "pre-requisites" section is now a "requirements" under the "Simple installation" heading.
This change also removes the Reddit link shield that links to the unused TinyPilot subreddit.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1856"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update README with more specific requirements

- bundler/bundle/install
Resolves #1857
This change refactors our installation blocks to use single conditions, fixing a bug when checking for Raspbian-based systems that allowed installations to proceed on 64-bit systems regardless of the OS version.
This also adds a check for a `FORCE_INSTALL` flag - setting the `FORCE_INSTALL` environment variable allows you to bypass the system checks to attempt an install on unsupported systems.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1858"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix install blocks

- get-tinypilot.sh
Resolves #1864 
This change updates `get-install.sh` to preserve the `FORCE_INSTALL` environment variable when running `sudo ./install`.
This allows users to set `FORCE_INSTALL` before running the simple install commands.
To test live on a device, install Raspberry Pi OS Bullseye 32-bit and run:
```bash
export FORCE_INSTALL=1
```
And then:
```bash
curl \
--silent \
--show-error \
https://raw.githubusercontent.com/tiny-pilot/tinypilot/refs/heads/1864-force_install-doesnt-work-as-expected/get-tinypilot.sh | \
bash - && \
sudo reboot
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1865"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix FORCE_INSTALL when using simple install commands

- .github/workflows/merge-pro.yml
Resolves #1884 
In a recent community commit merge to Pro, we had [a question](https://github.com/tiny-pilot/tinypilot-pro/pull/1509#issuecomment-2901315522) around which style of merge to use (regular or rebase) when updating the branch with Pro's `master`.
This change updates the body text of community-changes PRs to suggest using "Update with merge commit" when updating the branch.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1885"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Update language around updating branch with latest master

- debian-pkg/debian/tinypilot.postinst
- debian-pkg/debian/tinypilot.preinst
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/978
This PR removes the temporary workarounds no longer needed since reaching the next checkpoint release after 2.6.0 (i.e., the 2.7.0 checkpoint release).
Notes
1. We're removing all the workarounds marked with the following issue URL:
- [`https://github.com/tiny-pilot/tinypilot-pro/issues/978`](https://github.com/tiny-pilot/tinypilot-pro/issues/978)
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1888"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Remove temporary workarounds since reaching next checkpoint release

- dev-scripts/dump-logs
Resolves #1799 
This change removes the deprecated `dump-logs` dev script that hasn't been used for years.
The canonical way for users to share debug logs is via the web UI (“System” → “Logs”).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1887"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Delete dump-logs dev script

- debian-pkg/opt/ustreamer-launcher/config-library/hdmi-to-usb.yml
Resolves https://github.com/tiny-pilot/tinypilot-pro/issues/1528
This change sets the default `ustreamer_desired_fps` value for USB capture devices for better performance with the newer version of ustreamer.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1890"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Add default ustreamer_desired_fps to hdmi-to-usb config

- .ruff.toml
- app/debug_logs.py
- app/hostname.py
- app/local_system.py
- app/network.py
- app/update/launcher.py
- app/update/launcher_test.py
- app/update_logs.py
- app/version.py
- app/video_service.py
- dev_requirements.txt
- scripts/update-service
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1594
This PR updates `ruff`, [migrates our ruff config to the newer format](https://docs.astral.sh/ruff/editors/migration/#migrating-from-ruff-lsp), enables [ruff's `flake8-bandit` rules](https://docs.astral.sh/ruff/rules/#flake8-bandit-s), and addresses the [Bandit security warnings raised](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/4829/workflows/5ef2a71e-986a-4dd2-b2e3-8b440caa47f0/jobs/36695?invite=true#step-103-14222_64), namely:
- [suspicious-url-open-usage (S310)](https://docs.astral.sh/ruff/rules/suspicious-url-open-usage/#suspicious-url-open-usage-s310)
- [subprocess-without-shell-equals-true (S603)](https://docs.astral.sh/ruff/rules/subprocess-without-shell-equals-true/#subprocess-without-shell-equals- …
> Add Bandit to CircleCI

- .circleci/config.yml
- CONTRIBUTING.md
- app/db/store.py
- app/license_notice.py
- app/secret_key.py
- app/secret_key_test.py
- app/static/third-party/janus-gateway/1.3.2/janus.js
- app/version.py
- debian-pkg/opt/tinypilot-privileged/scripts/update
- dev-scripts/check-all
- dev-scripts/check-security
- dev_requirements.txt
- quick-install
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1595
This PR runs [Semgrep](https://github.com/semgrep/semgrep), a Static Application Security Testing (SAST) tool, on our code in CircleCI.
This PR also addresses Semgrep's [9 initial findings](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/4840/workflows/b0fb5361-fcb6-462e-bcbe-53dc42e16af9/jobs/36859?invite=true#step-104-1533_19).
Notes:
1. Seeing as Semgrep runs SAST on multiple languages (not just Python), we run it via a new `dev-scripts/check-security` script.
2. We only use the free version of Semgrep (i.e., [local scans](https://semgrep.dev/docs/getting-started/cli)). Otherwise, Semgrep want us to login and pay for additional security rules.
3. Semgrep flagged `janus.js` as allowing any origin (i.e., `*`) …
> Add Semgrep in CircleCI

- debian-pkg/usr/share/tinypilot/nginx_response_headers.conf
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1593
We accidentally broke the sharing of debug logs via the "Get Shareable URL" button on the "Debug Logs" dialog, when adding the Content Security Policy (CSP) HTTP header:
- https://github.com/tiny-pilot/tinypilot/blob/027c35a31309d98b6088e6ab6be742a362683574/debian-pkg/usr/share/tinypilot/nginx_response_headers.conf#L1-L3
Screenshot of the issue:
This PR updates the [`connect-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy/connect-src) value of the Content Security Policy (CSP) header to allow requests to `https://logs.tinypilotkvm.com`.
> Fix connect-src of Content Security Policy HTTP header

- app/templates/custom-elements/wifi-dialog.html
As [discovered here](https://github.com/tiny-pilot/tinypilot-pro/issues/1618#issuecomment-3361292481), we've broken the wifi-dialog via https://github.com/tiny-pilot/tinypilot/pull/1902.
The issue is that we've previously changed the output of the `/api/network/status` endpoint to return a list of network interfaces, but we forgot to update the endpoint's usage in wifi-dialog.
This PR fixes the usage of the `/api/network/status` endpoint in wifi-dialog.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1921"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> Fix wifi-dialog
